//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:56 PM CEST 
//


package org.proteored.miapeapi.xml.mzidentml.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *  The upper-most hierarchy level of mzIdentML with
 * 				sub-containers for example describing software, protocols and search
 * 				results (spectrum identifications or protein detection results).
 * 			
 * 
 * <p>Java class for PSI-PI.Main.mzIdentMLType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PSI-PI.Main.mzIdentMLType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://psidev.info/psi/pi/mzIdentML/1.0}FuGE.Common.IdentifiableType">
 *       &lt;sequence>
 *         &lt;element name="cvList" type="{http://psidev.info/psi/pi/mzIdentML/1.0}cvListType"/>
 *         &lt;element name="AnalysisSoftwareList" type="{http://psidev.info/psi/pi/mzIdentML/1.0}AnalysisSoftwareListType" minOccurs="0"/>
 *         &lt;element ref="{http://psidev.info/psi/pi/mzIdentML/1.0}Provider" minOccurs="0"/>
 *         &lt;element ref="{http://psidev.info/psi/pi/mzIdentML/1.0}AuditCollection" minOccurs="0"/>
 *         &lt;element name="AnalysisSampleCollection" type="{http://psidev.info/psi/pi/mzIdentML/1.0}AnalysisSampleCollectionType" minOccurs="0"/>
 *         &lt;element name="SequenceCollection" type="{http://psidev.info/psi/pi/mzIdentML/1.0}SequenceCollectionType" minOccurs="0"/>
 *         &lt;element name="AnalysisCollection" type="{http://psidev.info/psi/pi/mzIdentML/1.0}AnalysisCollectionType"/>
 *         &lt;element name="AnalysisProtocolCollection" type="{http://psidev.info/psi/pi/mzIdentML/1.0}AnalysisProtocolCollectionType"/>
 *         &lt;element name="DataCollection" type="{http://psidev.info/psi/pi/mzIdentML/1.0}DataCollectionType"/>
 *         &lt;element ref="{http://psidev.info/psi/pi/mzIdentML/1.0}BibliographicReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="version" use="required" type="{http://psidev.info/psi/pi/mzIdentML/1.0}versionRegex" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSI-PI.Main.mzIdentMLType", propOrder = {
    "cvList",
    "analysisSoftwareList",
    "provider",
    "auditCollection",
    "analysisSampleCollection",
    "sequenceCollection",
    "analysisCollection",
    "analysisProtocolCollection",
    "dataCollection",
    "bibliographicReference"
})
@XmlSeeAlso({
    MzIdentML.class
})
public class PSIPIMainMzIdentMLType
    extends FuGECommonIdentifiableType
{

    @XmlElement(required = true)
    protected CvListType cvList;
    @XmlElement(name = "AnalysisSoftwareList")
    protected AnalysisSoftwareListType analysisSoftwareList;
    @XmlElement(name = "Provider")
    protected FuGECollectionProviderType provider;
    @XmlElement(name = "AuditCollection")
    protected FuGECollectionAuditCollectionType auditCollection;
    @XmlElement(name = "AnalysisSampleCollection")
    protected AnalysisSampleCollectionType analysisSampleCollection;
    @XmlElement(name = "SequenceCollection")
    protected SequenceCollectionType sequenceCollection;
    @XmlElement(name = "AnalysisCollection", required = true)
    protected AnalysisCollectionType analysisCollection;
    @XmlElement(name = "AnalysisProtocolCollection", required = true)
    protected AnalysisProtocolCollectionType analysisProtocolCollection;
    @XmlElement(name = "DataCollection", required = true)
    protected DataCollectionType dataCollection;
    @XmlElement(name = "BibliographicReference")
    protected List<FuGECommonReferencesBibliographicReferenceType> bibliographicReference;
    @XmlAttribute
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the cvList property.
     * 
     * @return
     *     possible object is
     *     {@link CvListType }
     *     
     */
    public CvListType getCvList() {
        return cvList;
    }

    /**
     * Sets the value of the cvList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CvListType }
     *     
     */
    public void setCvList(CvListType value) {
        this.cvList = value;
    }

    /**
     * Gets the value of the analysisSoftwareList property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisSoftwareListType }
     *     
     */
    public AnalysisSoftwareListType getAnalysisSoftwareList() {
        return analysisSoftwareList;
    }

    /**
     * Sets the value of the analysisSoftwareList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisSoftwareListType }
     *     
     */
    public void setAnalysisSoftwareList(AnalysisSoftwareListType value) {
        this.analysisSoftwareList = value;
    }

    /**
     * The Provider of the mzIdentML record in terms
     * 								of the contact and software.
     * 
     * @return
     *     possible object is
     *     {@link FuGECollectionProviderType }
     *     
     */
    public FuGECollectionProviderType getProvider() {
        return provider;
    }

    /**
     * The Provider of the mzIdentML record in terms
     * 								of the contact and software.
     * 
     * @param value
     *     allowed object is
     *     {@link FuGECollectionProviderType }
     *     
     */
    public void setProvider(FuGECollectionProviderType value) {
        this.provider = value;
    }

    /**
     * The complete set of Contacts (people and
     * 								organisations) for this file.
     * 
     * @return
     *     possible object is
     *     {@link FuGECollectionAuditCollectionType }
     *     
     */
    public FuGECollectionAuditCollectionType getAuditCollection() {
        return auditCollection;
    }

    /**
     * The complete set of Contacts (people and
     * 								organisations) for this file.
     * 
     * @param value
     *     allowed object is
     *     {@link FuGECollectionAuditCollectionType }
     *     
     */
    public void setAuditCollection(FuGECollectionAuditCollectionType value) {
        this.auditCollection = value;
    }

    /**
     * Gets the value of the analysisSampleCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisSampleCollectionType }
     *     
     */
    public AnalysisSampleCollectionType getAnalysisSampleCollection() {
        return analysisSampleCollection;
    }

    /**
     * Sets the value of the analysisSampleCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisSampleCollectionType }
     *     
     */
    public void setAnalysisSampleCollection(AnalysisSampleCollectionType value) {
        this.analysisSampleCollection = value;
    }

    /**
     * Gets the value of the sequenceCollection property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceCollectionType }
     *     
     */
    public SequenceCollectionType getSequenceCollection() {
        return sequenceCollection;
    }

    /**
     * Sets the value of the sequenceCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceCollectionType }
     *     
     */
    public void setSequenceCollection(SequenceCollectionType value) {
        this.sequenceCollection = value;
    }

    /**
     * Gets the value of the analysisCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisCollectionType }
     *     
     */
    public AnalysisCollectionType getAnalysisCollection() {
        return analysisCollection;
    }

    /**
     * Sets the value of the analysisCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisCollectionType }
     *     
     */
    public void setAnalysisCollection(AnalysisCollectionType value) {
        this.analysisCollection = value;
    }

    /**
     * Gets the value of the analysisProtocolCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisProtocolCollectionType }
     *     
     */
    public AnalysisProtocolCollectionType getAnalysisProtocolCollection() {
        return analysisProtocolCollection;
    }

    /**
     * Sets the value of the analysisProtocolCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisProtocolCollectionType }
     *     
     */
    public void setAnalysisProtocolCollection(AnalysisProtocolCollectionType value) {
        this.analysisProtocolCollection = value;
    }

    /**
     * Gets the value of the dataCollection property.
     * 
     * @return
     *     possible object is
     *     {@link DataCollectionType }
     *     
     */
    public DataCollectionType getDataCollection() {
        return dataCollection;
    }

    /**
     * Sets the value of the dataCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCollectionType }
     *     
     */
    public void setDataCollection(DataCollectionType value) {
        this.dataCollection = value;
    }

    /**
     * Any bibliographic references associated with
     * 								the file Gets the value of the bibliographicReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibliographicReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBibliographicReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FuGECommonReferencesBibliographicReferenceType }
     * 
     * 
     */
    public List<FuGECommonReferencesBibliographicReferenceType> getBibliographicReference() {
        if (bibliographicReference == null) {
            bibliographicReference = new ArrayList<FuGECommonReferencesBibliographicReferenceType>();
        }
        return this.bibliographicReference;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
