//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 04:01:56 PM CEST 
//


package org.proteored.miapeapi.xml.msi.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SearchType" type="{}ParamType" minOccurs="0"/>
 *         &lt;element name="Taxonomy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumEntries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Cleavage_Name" type="{}ParamType" minOccurs="0"/>
 *         &lt;element name="Cleavage_Rules" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Misscleavages" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Additional_Cleavages" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AA_Modif" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Min_score" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Precursor_Mass_Tolerance" type="{}MIAPE_ParamUnit_Type" minOccurs="0"/>
 *         &lt;element name="Fragment_Mass_Tolerance" type="{}MIAPE_ParamUnit_Type" minOccurs="0"/>
 *         &lt;element name="PMF_Mass_Tolerance" type="{}MIAPE_ParamUnit_Type" minOccurs="0"/>
 *         &lt;element name="Scoring_Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Software_Ref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MSI_Additional_Parameter" type="{}ParamType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}MSI_Database" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "searchType",
    "taxonomy",
    "numEntries",
    "cleavageName",
    "cleavageRules",
    "misscleavages",
    "additionalCleavages",
    "aaModif",
    "minScore",
    "precursorMassTolerance",
    "fragmentMassTolerance",
    "pmfMassTolerance",
    "scoringAlgorithm",
    "softwareRef",
    "msiAdditionalParameter",
    "msiDatabase"
})
@XmlRootElement(name = "MSI_Input_Parameters")
public class MSIInputParameters {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "SearchType")
    protected ParamType searchType;
    @XmlElement(name = "Taxonomy")
    protected String taxonomy;
    @XmlElement(name = "NumEntries")
    protected String numEntries;
    @XmlElement(name = "Cleavage_Name")
    protected ParamType cleavageName;
    @XmlElement(name = "Cleavage_Rules")
    protected String cleavageRules;
    @XmlElement(name = "Misscleavages")
    protected String misscleavages;
    @XmlElement(name = "Additional_Cleavages")
    protected String additionalCleavages;
    @XmlElement(name = "AA_Modif")
    protected String aaModif;
    @XmlElement(name = "Min_score")
    protected String minScore;
    @XmlElement(name = "Precursor_Mass_Tolerance")
    protected MIAPEParamUnitType precursorMassTolerance;
    @XmlElement(name = "Fragment_Mass_Tolerance")
    protected MIAPEParamUnitType fragmentMassTolerance;
    @XmlElement(name = "PMF_Mass_Tolerance")
    protected MIAPEParamUnitType pmfMassTolerance;
    @XmlElement(name = "Scoring_Algorithm")
    protected String scoringAlgorithm;
    @XmlElement(name = "Software_Ref")
    protected String softwareRef;
    @XmlElement(name = "MSI_Additional_Parameter")
    protected List<ParamType> msiAdditionalParameter;
    @XmlElement(name = "MSI_Database")
    protected List<MSIDatabase> msiDatabase;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the searchType property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getSearchType() {
        return searchType;
    }

    /**
     * Sets the value of the searchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setSearchType(ParamType value) {
        this.searchType = value;
    }

    /**
     * Gets the value of the taxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxonomy() {
        return taxonomy;
    }

    /**
     * Sets the value of the taxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxonomy(String value) {
        this.taxonomy = value;
    }

    /**
     * Gets the value of the numEntries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumEntries() {
        return numEntries;
    }

    /**
     * Sets the value of the numEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumEntries(String value) {
        this.numEntries = value;
    }

    /**
     * Gets the value of the cleavageName property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getCleavageName() {
        return cleavageName;
    }

    /**
     * Sets the value of the cleavageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setCleavageName(ParamType value) {
        this.cleavageName = value;
    }

    /**
     * Gets the value of the cleavageRules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCleavageRules() {
        return cleavageRules;
    }

    /**
     * Sets the value of the cleavageRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCleavageRules(String value) {
        this.cleavageRules = value;
    }

    /**
     * Gets the value of the misscleavages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisscleavages() {
        return misscleavages;
    }

    /**
     * Sets the value of the misscleavages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisscleavages(String value) {
        this.misscleavages = value;
    }

    /**
     * Gets the value of the additionalCleavages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalCleavages() {
        return additionalCleavages;
    }

    /**
     * Sets the value of the additionalCleavages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalCleavages(String value) {
        this.additionalCleavages = value;
    }

    /**
     * Gets the value of the aaModif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAAModif() {
        return aaModif;
    }

    /**
     * Sets the value of the aaModif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAAModif(String value) {
        this.aaModif = value;
    }

    /**
     * Gets the value of the minScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinScore() {
        return minScore;
    }

    /**
     * Sets the value of the minScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinScore(String value) {
        this.minScore = value;
    }

    /**
     * Gets the value of the precursorMassTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link MIAPEParamUnitType }
     *     
     */
    public MIAPEParamUnitType getPrecursorMassTolerance() {
        return precursorMassTolerance;
    }

    /**
     * Sets the value of the precursorMassTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIAPEParamUnitType }
     *     
     */
    public void setPrecursorMassTolerance(MIAPEParamUnitType value) {
        this.precursorMassTolerance = value;
    }

    /**
     * Gets the value of the fragmentMassTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link MIAPEParamUnitType }
     *     
     */
    public MIAPEParamUnitType getFragmentMassTolerance() {
        return fragmentMassTolerance;
    }

    /**
     * Sets the value of the fragmentMassTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIAPEParamUnitType }
     *     
     */
    public void setFragmentMassTolerance(MIAPEParamUnitType value) {
        this.fragmentMassTolerance = value;
    }

    /**
     * Gets the value of the pmfMassTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link MIAPEParamUnitType }
     *     
     */
    public MIAPEParamUnitType getPMFMassTolerance() {
        return pmfMassTolerance;
    }

    /**
     * Sets the value of the pmfMassTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIAPEParamUnitType }
     *     
     */
    public void setPMFMassTolerance(MIAPEParamUnitType value) {
        this.pmfMassTolerance = value;
    }

    /**
     * Gets the value of the scoringAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoringAlgorithm() {
        return scoringAlgorithm;
    }

    /**
     * Sets the value of the scoringAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoringAlgorithm(String value) {
        this.scoringAlgorithm = value;
    }

    /**
     * Gets the value of the softwareRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareRef() {
        return softwareRef;
    }

    /**
     * Sets the value of the softwareRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareRef(String value) {
        this.softwareRef = value;
    }

    /**
     * Gets the value of the msiAdditionalParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msiAdditionalParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMSIAdditionalParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getMSIAdditionalParameter() {
        if (msiAdditionalParameter == null) {
            msiAdditionalParameter = new ArrayList<ParamType>();
        }
        return this.msiAdditionalParameter;
    }

    /**
     * Gets the value of the msiDatabase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msiDatabase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMSIDatabase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MSIDatabase }
     * 
     * 
     */
    public List<MSIDatabase> getMSIDatabase() {
        if (msiDatabase == null) {
            msiDatabase = new ArrayList<MSIDatabase>();
        }
        return this.msiDatabase;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
