//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 04:01:56 PM CEST 
//

package org.proteored.miapeapi.xml.msi.autogenerated;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import edu.scripps.yates.utilities.staticstorage.StaticStrings;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PeptideScore" type="{}ParamType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Spectrum_Ref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Charge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Mass_Deviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Input_Data_Ref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RT" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{}MSI_PeptideModification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Protein_Refs" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sequence", "peptideScore", "spectrumRef", "charge", "massDeviation", "inputDataRef",
		"rt", "rank", "msiPeptideModification", "proteinRefs" })
@XmlRootElement(name = "MSI_Identified_Peptide")
public class MSIIdentifiedPeptide {

	@XmlElement(name = "Sequence", required = true)
	protected String sequence;
	@XmlElement(name = "PeptideScore")
	protected List<ParamType> peptideScore;
	@XmlElement(name = "Spectrum_Ref")
	protected String spectrumRef;
	@XmlElement(name = "Charge")
	protected String charge;
	@XmlElement(name = "Mass_Deviation")
	protected String massDeviation;
	@XmlElement(name = "Input_Data_Ref")
	protected String inputDataRef;
	@XmlElement(name = "RT")
	protected Double rt;
	@XmlElement(name = "Rank")
	protected Integer rank;
	@XmlElement(name = "MSI_PeptideModification")
	protected List<MSIPeptideModification> msiPeptideModification;
	@XmlElement(name = "Protein_Refs")
	protected ProteinRefs proteinRefs;
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/**
	 * Gets the value of the sequence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSequence() {
		return sequence;
	}

	/**
	 * Sets the value of the sequence property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSequence(String value) {
		sequence = value;
	}

	/**
	 * Gets the value of the peptideScore property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the peptideScore property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPeptideScore().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ParamType
	 * }
	 * 
	 * 
	 */
	public List<ParamType> getPeptideScore() {
		if (peptideScore == null) {
			peptideScore = new ArrayList<ParamType>();
		}
		return peptideScore;
	}

	/**
	 * Gets the value of the spectrumRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpectrumRef() {
		return spectrumRef;
	}

	/**
	 * Sets the value of the spectrumRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpectrumRef(String value) {
		spectrumRef = value;
	}

	/**
	 * Gets the value of the charge property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCharge() {
		return charge;
	}

	/**
	 * Sets the value of the charge property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCharge(String value) {
		charge = StaticStrings.getUniqueInstance(value);
	}

	/**
	 * Gets the value of the massDeviation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMassDeviation() {
		return massDeviation;
	}

	/**
	 * Sets the value of the massDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMassDeviation(String value) {
		massDeviation = StaticStrings.getUniqueInstance(value);
	}

	/**
	 * Gets the value of the inputDataRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInputDataRef() {
		return inputDataRef;
	}

	/**
	 * Sets the value of the inputDataRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInputDataRef(String value) {
		inputDataRef = value;
	}

	/**
	 * Gets the value of the rt property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getRT() {
		return rt;
	}

	/**
	 * Sets the value of the rt property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setRT(Double value) {
		rt = value;
	}

	/**
	 * Gets the value of the rank property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * Sets the value of the rank property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setRank(Integer value) {
		rank = value;
	}

	/**
	 * Gets the value of the msiPeptideModification property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the msiPeptideModification property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMSIPeptideModification().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MSIPeptideModification }
	 * 
	 * 
	 */
	public List<MSIPeptideModification> getMSIPeptideModification() {
		if (msiPeptideModification == null) {
			msiPeptideModification = new ArrayList<MSIPeptideModification>();
		}
		return msiPeptideModification;
	}

	/**
	 * the identifiers of the proteins to which this peptide belongs to
	 * 
	 * @return possible object is {@link ProteinRefs }
	 * 
	 */
	public ProteinRefs getProteinRefs() {
		return proteinRefs;
	}

	/**
	 * Sets the value of the proteinRefs property.
	 * 
	 * @param value
	 *            allowed object is {@link ProteinRefs }
	 * 
	 */
	public void setProteinRefs(ProteinRefs value) {
		proteinRefs = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		id = value;
	}

}
