package org.proteored.miapeapi.xml.gi.adapter;

import org.proteored.miapeapi.cv.gi.FeatureDetectionAlgorithmName;
import org.proteored.miapeapi.interfaces.Adapter;
import org.proteored.miapeapi.interfaces.gi.FeatureDetection;
import org.proteored.miapeapi.xml.gi.autogenerated.GIFeatureDetectionType;
import org.proteored.miapeapi.xml.gi.autogenerated.ObjectFactory;
import org.proteored.miapeapi.xml.gi.util.GIControlVocabularyXmlFactory;

public class FeatureDetectionAdapter implements Adapter<GIFeatureDetectionType> {
	private final FeatureDetection featureDetection;
	private final ObjectFactory factory;
	private final GIControlVocabularyXmlFactory cvFactory;

	public FeatureDetectionAdapter(FeatureDetection featureDetection, ObjectFactory factory,
			GIControlVocabularyXmlFactory cvFactory) {
		this.factory = factory;
		this.featureDetection = featureDetection;
		this.cvFactory = cvFactory;
	}

	@Override
	public GIFeatureDetectionType adapt() {
		GIFeatureDetectionType xmlFeatureDetection = factory.createGIFeatureDetectionType();
		xmlFeatureDetection.setEditing(featureDetection.getEditing());
		xmlFeatureDetection.setStepOrder(featureDetection.getStepOrder());
		xmlFeatureDetection.setCatalogNumber(featureDetection.getCatalogNumber());
		xmlFeatureDetection.setComments(featureDetection.getComments());
		xmlFeatureDetection.setDescription(featureDetection.getDescription());
		xmlFeatureDetection.setManufacturer(featureDetection.getManufacturer());
		xmlFeatureDetection.setModel(featureDetection.getModel());
		xmlFeatureDetection.setName(cvFactory.createCV(featureDetection.getName(), null,
				FeatureDetectionAlgorithmName.getInstance(cvFactory.getCvManager())));
		xmlFeatureDetection.setParameters(featureDetection.getParameters());
		xmlFeatureDetection.setURI(featureDetection.getURI());
		xmlFeatureDetection.setVersion(featureDetection.getVersion());
		return xmlFeatureDetection;
	}

}
