package org.proteored.miapeapi.xml.pride.msi;

import org.proteored.miapeapi.interfaces.msi.PeptideScore;
import org.proteored.miapeapi.xml.pride.autogenerated.CvParamType;
import org.proteored.miapeapi.xml.pride.autogenerated.UserParamType;

public class PeptideScoreImpl implements PeptideScore {
	private final CvParamType prideCvParam;
	private final UserParamType prideUserParam;

	public PeptideScoreImpl(CvParamType cvParam) {
		this.prideCvParam = cvParam;
		this.prideUserParam = null;
	}

	public PeptideScoreImpl(UserParamType userParam) {
		this.prideCvParam = null;
		this.prideUserParam = userParam;
	}

	@Override
	public String getName() {
		if (prideCvParam != null)
			return prideCvParam.getName();
		else if (prideUserParam != null)
			return prideUserParam.getName();
		return null;
	}

	@Override
	public String getValue() {
		if (prideCvParam != null)
			return prideCvParam.getValue();
		else if (prideUserParam != null)
			return prideUserParam.getValue();
		return null;
	}
}
