package org.proteored.miapeapi.xml.ge.adapter;

import org.proteored.miapeapi.cv.ge.BufferComponentName;
import org.proteored.miapeapi.interfaces.Substance;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;
import org.proteored.miapeapi.xml.ge.autogenerated.ObjectFactory;
import org.proteored.miapeapi.xml.ge.util.GEControlVocabularyXmlFactory;

public class BufferComponentAdapter extends SubstanceAdapter {

	public BufferComponentAdapter(Substance substance2, ObjectFactory factory2,
			GEControlVocabularyXmlFactory cvFactory2) {
		super(substance2, factory2, cvFactory2);
	}

	@Override
	public MIAPESubstanceType adapt() {
		MIAPESubstanceType substanceXML = super.adapt();
		substanceXML.setName(super.cvFactory.createCV(super.substance.getName(), null,
				BufferComponentName.getInstance(cvFactory.getCvManager())));
		return substanceXML;
	}

}
