package org.proteored.miapeapi.xml.ge.adapter;

import org.proteored.miapeapi.cv.ge.IndirectDetectionAgentName;
import org.proteored.miapeapi.interfaces.ge.IndirectDetectionAgent;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;
import org.proteored.miapeapi.xml.ge.autogenerated.ObjectFactory;
import org.proteored.miapeapi.xml.ge.util.GEControlVocabularyXmlFactory;

public class IndirectDetectionAgentAdapter extends SubstanceAdapter {

	public IndirectDetectionAgentAdapter(IndirectDetectionAgent substance2, ObjectFactory factory2,
			GEControlVocabularyXmlFactory cvFactory2) {
		super(substance2, factory2, cvFactory2);
	}

	@Override
	public MIAPESubstanceType adapt() {
		MIAPESubstanceType substanceXML = super.adapt();
		substanceXML.setName(super.cvFactory.createCV(super.substance.getName(), null,
				IndirectDetectionAgentName.getInstance(cvFactory.getCvManager())));

		return substanceXML;
	}

}
