package org.proteored.miapeapi.xml.ge.adapter;

import java.util.List;
import java.util.Set;

import org.proteored.miapeapi.interfaces.Adapter;
import org.proteored.miapeapi.interfaces.Buffer;
import org.proteored.miapeapi.interfaces.Equipment;
import org.proteored.miapeapi.interfaces.ge.Agent;
import org.proteored.miapeapi.interfaces.ge.InterdimensionProcess;
import org.proteored.miapeapi.xml.ge.autogenerated.GEInterDimensionProcess;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPEBufferType;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPEGEEquipmentType;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;
import org.proteored.miapeapi.xml.ge.autogenerated.ObjectFactory;
import org.proteored.miapeapi.xml.ge.util.GEControlVocabularyXmlFactory;

public class InterdimensionProcessAdapter implements Adapter<GEInterDimensionProcess> {
	private final InterdimensionProcess interdimensionProcess;
	private final ObjectFactory factory;
	private final GEControlVocabularyXmlFactory cvFactory;


	public InterdimensionProcessAdapter(
			InterdimensionProcess interdimensionProcess2,
			ObjectFactory factory2, GEControlVocabularyXmlFactory cvFactory2) {
		this.cvFactory = cvFactory2;
		this.factory = factory2;
		this.interdimensionProcess = interdimensionProcess2;
	}


	@Override
	public GEInterDimensionProcess adapt() {
		GEInterDimensionProcess interdimensionProcessXML = factory.createGEInterDimensionProcess();
		interdimensionProcessXML.setName(interdimensionProcess.getName());
		interdimensionProcessXML.setProtocol(interdimensionProcess.getProtocol());

		if (interdimensionProcess.getInterdimensionBuffers() != null)
			addBuffer(interdimensionProcessXML.getGEInterDimensionBuffer(), interdimensionProcess.getInterdimensionBuffers());

		if (interdimensionProcess.getInterdimensionReagents() != null)
			addSubstance(interdimensionProcessXML.getGEInterDimensionReagent(), interdimensionProcess.getInterdimensionReagents());

		if (interdimensionProcess.getInterdimensionEquipments() != null)
			addEquipment(interdimensionProcessXML.getGEInterDimensionEquipment(), interdimensionProcess.getInterdimensionEquipments());

		return interdimensionProcessXML;
	}


	private void addEquipment(
			List<MIAPEGEEquipmentType> geInterDimensionEquipment,
			Set<Equipment> interdimensionEquipments) {
		for (Equipment equipment : interdimensionEquipments)
			geInterDimensionEquipment.add(new EquipmentAdapter(equipment, factory, cvFactory).adapt());

	}


	private void addSubstance(List<MIAPESubstanceType> geInterDimensionReagent,
			Set<Agent> set) {
		for (Agent substance : set)
			geInterDimensionReagent.add(new AgentAdapter(substance, factory, cvFactory).adapt());

	}


	private void addBuffer(List<MIAPEBufferType> geInterDimensionBuffer,
			Set<Buffer> interdimensionBuffers) {
		for (Buffer buffer : interdimensionBuffers)
			geInterDimensionBuffer.add(new BufferAdapter(buffer, factory, cvFactory).adapt());

	}

}
