//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.19 at 01:51:42 PM CEST 
//


package org.proteored.miapeapi.xml.ms.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 *  The interface that is the use of a Parameterizable class. 
 * 
 * <p>Java class for FuGE.Common.Protocol.ParameterizableApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FuGE.Common.Protocol.ParameterizableApplicationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}FuGE.Common.IdentifiableType">
 *       &lt;sequence>
 *         &lt;element ref="{}ParameterValue" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FuGE.Common.Protocol.ParameterizableApplicationType", propOrder = {
    "parameterValue"
})
@XmlSeeAlso({
    FuGECommonProtocolSoftwareApplicationType.class,
    FuGECommonProtocolActionApplicationType.class,
    FuGECommonProtocolEquipmentApplicationType.class
})
public abstract class FuGECommonProtocolParameterizableApplicationType
    extends FuGECommonIdentifiableType
{

    @XmlElement(name = "ParameterValue")
    protected List<FuGECommonProtocolParameterValueType> parameterValue;

    /**
     *  The parameter values for this Parameterizable Application. Gets the value of the parameterValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FuGECommonProtocolParameterValueType }
     * 
     * 
     */
    public List<FuGECommonProtocolParameterValueType> getParameterValue() {
        if (parameterValue == null) {
            parameterValue = new ArrayList<FuGECommonProtocolParameterValueType>();
        }
        return this.parameterValue;
    }

}
