package org.proteored.miapeapi.xml.mzidentml;

import org.proteored.miapeapi.cv.Accession;
import org.proteored.miapeapi.cv.ControlVocabularyManager;
import org.proteored.miapeapi.cv.ms.SoftwareName;
import org.proteored.miapeapi.interfaces.Software;
import org.proteored.miapeapi.xml.mzidentml.autogenerated.FuGECommonAuditContactType;
import org.proteored.miapeapi.xml.mzidentml.autogenerated.FuGECommonOntologyCvParamType;
import org.proteored.miapeapi.xml.mzidentml.autogenerated.FuGECommonOntologyParamType;
import org.proteored.miapeapi.xml.mzidentml.autogenerated.FuGECommonOntologyUserParamType;
import org.proteored.miapeapi.xml.mzidentml.autogenerated.PSIPIAnalysisSearchAnalysisSoftwareType;
import org.proteored.miapeapi.xml.mzidentml.autogenerated.ParamListType;
import org.proteored.miapeapi.xml.mzidentml.util.MzidentmlControlVocabularyXmlFactory;
import org.proteored.miapeapi.xml.util.MiapeXmlUtil;

public class ValidationSoftwareImpl implements Software {
	private final PSIPIAnalysisSearchAnalysisSoftwareType softwareXML;
	private final FuGECommonAuditContactType softwareContactXML;
	private final ParamListType analysisParams;
	private final ParamListType thresholds;
	private final ControlVocabularyManager cvManager;

	public ValidationSoftwareImpl(PSIPIAnalysisSearchAnalysisSoftwareType softwareXML,
			FuGECommonAuditContactType softwareContactXML, ParamListType analysisParams,
			ParamListType thresholds, ControlVocabularyManager cvManager) {
		this.softwareContactXML = softwareContactXML;
		this.softwareXML = softwareXML;
		this.analysisParams = analysisParams;
		this.thresholds = thresholds;
		this.cvManager = cvManager;
	}

	@Override
	public String getCatalogNumber() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getComments() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getCustomizations() {
		return softwareXML.getCustomizations();
	}

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int getId() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public String getManufacturer() {
		if (this.softwareContactXML != null)
			return softwareContactXML.getName();
		return null;
	}

	@Override
	public String getModel() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getName() {
		if (softwareXML.getSoftwareName() != null) {
			FuGECommonOntologyCvParamType cvParam = softwareXML.getSoftwareName().getCvParam();
			if (cvParam != null) {
				if (cvManager.isSonOf(new Accession(cvParam.getAccession()),
						SoftwareName.CV_SOFTWARE)) {
					return cvParam.getName();
				}
			}
			FuGECommonOntologyUserParamType userParam = softwareXML.getSoftwareName()
					.getUserParam();
			if (userParam != null) {
				return userParam.getName();
			}
		}
		return softwareXML.getName();
	}

	@Override
	public String getParameters() {
		StringBuilder sb = new StringBuilder();
		// Analysis params
		if (analysisParams != null) {
			for (FuGECommonOntologyParamType param : analysisParams.getParamGroup()) {
				sb.append(MzidentmlControlVocabularyXmlFactory.readEntireParam(param));
				sb.append(MiapeXmlUtil.TERM_SEPARATOR);
			}
		}
		if (thresholds != null) {
			for (FuGECommonOntologyParamType param : thresholds.getParamGroup()) {
				sb.append(MzidentmlControlVocabularyXmlFactory.readEntireParam(param));
				sb.append(MiapeXmlUtil.TERM_SEPARATOR);
			}
		}
		return sb.toString();
	}

	@Override
	public String getURI() {
		return softwareXML.getURI();
	}

	@Override
	public String getVersion() {
		return softwareXML.getVersion();
	}

}
