//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.18 at 02:51:39 PM CEST 
//


package org.proteored.miapeapi.xml.gi.autogenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Feature_List" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Feature_URI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Matches_List" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Matches_URI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Results_Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Results_URI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "featureList",
    "featureURI",
    "matchesList",
    "matchesURI",
    "resultsDescription",
    "resultsURI"
})
@XmlRootElement(name = "GI_Data_Reporting")
public class GIDataReporting {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Feature_List")
    protected String featureList;
    @XmlElement(name = "Feature_URI")
    @XmlSchemaType(name = "anyURI")
    protected String featureURI;
    @XmlElement(name = "Matches_List")
    protected String matchesList;
    @XmlElement(name = "Matches_URI")
    @XmlSchemaType(name = "anyURI")
    protected String matchesURI;
    @XmlElement(name = "Results_Description")
    protected String resultsDescription;
    @XmlElement(name = "Results_URI")
    @XmlSchemaType(name = "anyURI")
    protected String resultsURI;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the featureList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureList() {
        return featureList;
    }

    /**
     * Sets the value of the featureList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureList(String value) {
        this.featureList = value;
    }

    /**
     * Gets the value of the featureURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureURI() {
        return featureURI;
    }

    /**
     * Sets the value of the featureURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureURI(String value) {
        this.featureURI = value;
    }

    /**
     * Gets the value of the matchesList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchesList() {
        return matchesList;
    }

    /**
     * Sets the value of the matchesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchesList(String value) {
        this.matchesList = value;
    }

    /**
     * Gets the value of the matchesURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchesURI() {
        return matchesURI;
    }

    /**
     * Sets the value of the matchesURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchesURI(String value) {
        this.matchesURI = value;
    }

    /**
     * Gets the value of the resultsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultsDescription() {
        return resultsDescription;
    }

    /**
     * Sets the value of the resultsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultsDescription(String value) {
        this.resultsDescription = value;
    }

    /**
     * Gets the value of the resultsURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultsURI() {
        return resultsURI;
    }

    /**
     * Sets the value of the resultsURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultsURI(String value) {
        this.resultsURI = value;
    }

}
