//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.18 at 02:51:39 PM CEST 
//


package org.proteored.miapeapi.xml.gi.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Step_Order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GI_Feature_Quantitation_Algorithm" type="{}MIAPE_Algorithm_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GI_Feature_Quantitation_Background" type="{}MIAPE_Algorithm_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GI_Feature_Quantitation_Normalization" type="{}MIAPE_Algorithm_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "type",
    "stepOrder",
    "giFeatureQuantitationAlgorithm",
    "giFeatureQuantitationBackground",
    "giFeatureQuantitationNormalization"
})
@XmlRootElement(name = "GI_Feature_Quantitation")
public class GIFeatureQuantitation {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "Step_Order")
    protected String stepOrder;
    @XmlElement(name = "GI_Feature_Quantitation_Algorithm")
    protected List<MIAPEAlgorithmType> giFeatureQuantitationAlgorithm;
    @XmlElement(name = "GI_Feature_Quantitation_Background")
    protected List<MIAPEAlgorithmType> giFeatureQuantitationBackground;
    @XmlElement(name = "GI_Feature_Quantitation_Normalization")
    protected List<MIAPEAlgorithmType> giFeatureQuantitationNormalization;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the stepOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepOrder() {
        return stepOrder;
    }

    /**
     * Sets the value of the stepOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepOrder(String value) {
        this.stepOrder = value;
    }

    /**
     * Gets the value of the giFeatureQuantitationAlgorithm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the giFeatureQuantitationAlgorithm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGIFeatureQuantitationAlgorithm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAPEAlgorithmType }
     * 
     * 
     */
    public List<MIAPEAlgorithmType> getGIFeatureQuantitationAlgorithm() {
        if (giFeatureQuantitationAlgorithm == null) {
            giFeatureQuantitationAlgorithm = new ArrayList<MIAPEAlgorithmType>();
        }
        return this.giFeatureQuantitationAlgorithm;
    }

    /**
     * Gets the value of the giFeatureQuantitationBackground property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the giFeatureQuantitationBackground property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGIFeatureQuantitationBackground().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAPEAlgorithmType }
     * 
     * 
     */
    public List<MIAPEAlgorithmType> getGIFeatureQuantitationBackground() {
        if (giFeatureQuantitationBackground == null) {
            giFeatureQuantitationBackground = new ArrayList<MIAPEAlgorithmType>();
        }
        return this.giFeatureQuantitationBackground;
    }

    /**
     * Gets the value of the giFeatureQuantitationNormalization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the giFeatureQuantitationNormalization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGIFeatureQuantitationNormalization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAPEAlgorithmType }
     * 
     * 
     */
    public List<MIAPEAlgorithmType> getGIFeatureQuantitationNormalization() {
        if (giFeatureQuantitationNormalization == null) {
            giFeatureQuantitationNormalization = new ArrayList<MIAPEAlgorithmType>();
        }
        return this.giFeatureQuantitationNormalization;
    }

}
