//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.18 at 02:51:39 PM CEST 
//


package org.proteored.miapeapi.xml.gi.autogenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GI_Image_Processing_Algorithm_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GI_Image_Processing_Algorithm_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{}MIAPE_Algorithm_Type">
 *       &lt;sequence>
 *         &lt;element name="Step_Order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GI_Image_Processing_Algorithm_Type", propOrder = {
    "stepOrder"
})
public class GIImageProcessingAlgorithmType
    extends MIAPEAlgorithmType
{

    @XmlElement(name = "Step_Order")
    protected String stepOrder;

    /**
     * Gets the value of the stepOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepOrder() {
        return stepOrder;
    }

    /**
     * Sets the value of the stepOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepOrder(String value) {
        this.stepOrder = value;
    }

}
