//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.18 at 02:51:38 PM CEST 
//


package org.proteored.miapeapi.xml.ge.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Protocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GE_InterDimension_Buffer" type="{}MIAPE_Buffer_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GE_InterDimension_Reagent" type="{}MIAPE_Substance_Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GE_InterDimension_Equipment" type="{}MIAPE_GE_Equipment_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "protocol",
    "geInterDimensionBuffer",
    "geInterDimensionReagent",
    "geInterDimensionEquipment"
})
@XmlRootElement(name = "GE_InterDimension_Process")
public class GEInterDimensionProcess {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Protocol")
    protected String protocol;
    @XmlElement(name = "GE_InterDimension_Buffer")
    protected List<MIAPEBufferType> geInterDimensionBuffer;
    @XmlElement(name = "GE_InterDimension_Reagent")
    protected List<MIAPESubstanceType> geInterDimensionReagent;
    @XmlElement(name = "GE_InterDimension_Equipment")
    protected List<MIAPEGEEquipmentType> geInterDimensionEquipment;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the geInterDimensionBuffer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geInterDimensionBuffer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGEInterDimensionBuffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAPEBufferType }
     * 
     * 
     */
    public List<MIAPEBufferType> getGEInterDimensionBuffer() {
        if (geInterDimensionBuffer == null) {
            geInterDimensionBuffer = new ArrayList<MIAPEBufferType>();
        }
        return this.geInterDimensionBuffer;
    }

    /**
     * Gets the value of the geInterDimensionReagent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geInterDimensionReagent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGEInterDimensionReagent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAPESubstanceType }
     * 
     * 
     */
    public List<MIAPESubstanceType> getGEInterDimensionReagent() {
        if (geInterDimensionReagent == null) {
            geInterDimensionReagent = new ArrayList<MIAPESubstanceType>();
        }
        return this.geInterDimensionReagent;
    }

    /**
     * Gets the value of the geInterDimensionEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geInterDimensionEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGEInterDimensionEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAPEGEEquipmentType }
     * 
     * 
     */
    public List<MIAPEGEEquipmentType> getGEInterDimensionEquipment() {
        if (geInterDimensionEquipment == null) {
            geInterDimensionEquipment = new ArrayList<MIAPEGEEquipmentType>();
        }
        return this.geInterDimensionEquipment;
    }

}
