//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.18 at 02:51:38 PM CEST 
//


package org.proteored.miapeapi.xml.ge.autogenerated;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.proteored.miapeapi.xml.ge.autogenerated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SoftwareApplication_QNAME = new QName("", "SoftwareApplication");
    private final static QName _Database_QNAME = new QName("", "Database");
    private final static QName _Organization_QNAME = new QName("", "Organization");
    private final static QName _ActionApplication_QNAME = new QName("", "ActionApplication");
    private final static QName _ParameterPair_QNAME = new QName("", "ParameterPair");
    private final static QName _GenericSoftware_QNAME = new QName("", "GenericSoftware");
    private final static QName _GenericMaterial_QNAME = new QName("", "GenericMaterial");
    private final static QName _UserParam_QNAME = new QName("", "userParam");
    private final static QName _PropertyValue_QNAME = new QName("", "PropertyValue");
    private final static QName _DatabaseReference_QNAME = new QName("", "DatabaseReference");
    private final static QName _GenericMaterialMeasurement_QNAME = new QName("", "GenericMaterialMeasurement");
    private final static QName _GenericAction_QNAME = new QName("", "GenericAction");
    private final static QName _GenericParameter_QNAME = new QName("", "GenericParameter");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _ContactRole_QNAME = new QName("", "ContactRole");
    private final static QName _EquipmentApplication_QNAME = new QName("", "EquipmentApplication");
    private final static QName _GenericProtocol_QNAME = new QName("", "GenericProtocol");
    private final static QName _GenericEquipment_QNAME = new QName("", "GenericEquipment");
    private final static QName _Cv_QNAME = new QName("", "cv");
    private final static QName _CvParam_QNAME = new QName("", "cvParam");
    private final static QName _ReferenceableCollection_QNAME = new QName("", "ReferenceableCollection");
    private final static QName _GenericProtocolApplication_QNAME = new QName("", "GenericProtocolApplication");
    private final static QName _ParameterValue_QNAME = new QName("", "ParameterValue");
    private final static QName _ExternalData_QNAME = new QName("", "ExternalData");
    private final static QName _AuditCollection_QNAME = new QName("", "AuditCollection");
    private final static QName _BibliographicReference_QNAME = new QName("", "BibliographicReference");
    private final static QName _Provider_QNAME = new QName("", "Provider");
    private final static QName _Person_QNAME = new QName("", "Person");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.proteored.miapeapi.xml.ge.autogenerated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementRangeType }
     * 
     */
    public FuGECommonMeasurementRangeType createFuGECommonMeasurementRangeType() {
        return new FuGECommonMeasurementRangeType();
    }

    /**
     * Create an instance of {@link GEDirectDetection }
     * 
     */
    public GEDirectDetection createGEDirectDetection() {
        return new GEDirectDetection();
    }

    /**
     * Create an instance of {@link FuGECommonAuditContactRoleType }
     * 
     */
    public FuGECommonAuditContactRoleType createFuGECommonAuditContactRoleType() {
        return new FuGECommonAuditContactRoleType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolType.Equipment }
     * 
     */
    public FuGECommonProtocolGenericProtocolType.Equipment createFuGECommonProtocolGenericProtocolTypeEquipment() {
        return new FuGECommonProtocolGenericProtocolType.Equipment();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolApplicationType }
     * 
     */
    public FuGECommonProtocolGenericProtocolApplicationType createFuGECommonProtocolGenericProtocolApplicationType() {
        return new FuGECommonProtocolGenericProtocolApplicationType();
    }

    /**
     * Create an instance of {@link MIAPEOwnerType }
     * 
     */
    public MIAPEOwnerType createMIAPEOwnerType() {
        return new MIAPEOwnerType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericEquipmentType }
     * 
     */
    public FuGECommonProtocolGenericEquipmentType createFuGECommonProtocolGenericEquipmentType() {
        return new FuGECommonProtocolGenericEquipmentType();
    }

    /**
     * Create an instance of {@link FuGEBioDataExternalDataType.FileFormat }
     * 
     */
    public FuGEBioDataExternalDataType.FileFormat createFuGEBioDataExternalDataTypeFileFormat() {
        return new FuGEBioDataExternalDataType.FileFormat();
    }

    /**
     * Create an instance of {@link FuGECommonAuditOrganizationType }
     * 
     */
    public FuGECommonAuditOrganizationType createFuGECommonAuditOrganizationType() {
        return new FuGECommonAuditOrganizationType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericSoftwareType }
     * 
     */
    public FuGECommonProtocolGenericSoftwareType createFuGECommonProtocolGenericSoftwareType() {
        return new FuGECommonProtocolGenericSoftwareType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericActionType }
     * 
     */
    public FuGECommonProtocolGenericActionType createFuGECommonProtocolGenericActionType() {
        return new FuGECommonProtocolGenericActionType();
    }

    /**
     * Create an instance of {@link FuGEBioMaterialGenericMaterialMeasurementType }
     * 
     */
    public FuGEBioMaterialGenericMaterialMeasurementType createFuGEBioMaterialGenericMaterialMeasurementType() {
        return new FuGEBioMaterialGenericMaterialMeasurementType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolParameterValueType }
     * 
     */
    public FuGECommonProtocolParameterValueType createFuGECommonProtocolParameterValueType() {
        return new FuGECommonProtocolParameterValueType();
    }

    /**
     * Create an instance of {@link GEImage }
     * 
     */
    public GEImage createGEImage() {
        return new GEImage();
    }

    /**
     * Create an instance of {@link FuGECommonOntologyCvType }
     * 
     */
    public FuGECommonOntologyCvType createFuGECommonOntologyCvType() {
        return new FuGECommonOntologyCvType();
    }

    /**
     * Create an instance of {@link GEInterDimensionProcess }
     * 
     */
    public GEInterDimensionProcess createGEInterDimensionProcess() {
        return new GEInterDimensionProcess();
    }

    /**
     * Create an instance of {@link GESample }
     * 
     */
    public GESample createGESample() {
        return new GESample();
    }

    /**
     * Create an instance of {@link FuGECommonDescriptionDescriptionType }
     * 
     */
    public FuGECommonDescriptionDescriptionType createFuGECommonDescriptionDescriptionType() {
        return new FuGECommonDescriptionDescriptionType();
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementBooleanValueType }
     * 
     */
    public FuGECommonMeasurementBooleanValueType createFuGECommonMeasurementBooleanValueType() {
        return new FuGECommonMeasurementBooleanValueType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolActionApplicationType.ActionDeviation }
     * 
     */
    public FuGECommonProtocolActionApplicationType.ActionDeviation createFuGECommonProtocolActionApplicationTypeActionDeviation() {
        return new FuGECommonProtocolActionApplicationType.ActionDeviation();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericParameterType.ParameterType }
     * 
     */
    public FuGECommonProtocolGenericParameterType.ParameterType createFuGECommonProtocolGenericParameterTypeParameterType() {
        return new FuGECommonProtocolGenericParameterType.ParameterType();
    }

    /**
     * Create an instance of {@link MIAPEGESoftwareType }
     * 
     */
    public MIAPEGESoftwareType createMIAPEGESoftwareType() {
        return new MIAPEGESoftwareType();
    }

    /**
     * Create an instance of {@link MIAPEAlgorithmType }
     * 
     */
    public MIAPEAlgorithmType createMIAPEAlgorithmType() {
        return new MIAPEAlgorithmType();
    }

    /**
     * Create an instance of {@link GEDimensionType }
     * 
     */
    public GEDimensionType createGEDimensionType() {
        return new GEDimensionType();
    }

    /**
     * Create an instance of {@link GEImageAcquisition }
     * 
     */
    public GEImageAcquisition createGEImageAcquisition() {
        return new GEImageAcquisition();
    }

    /**
     * Create an instance of {@link FuGECollectionReferenceableCollectionType }
     * 
     */
    public FuGECollectionReferenceableCollectionType createFuGECollectionReferenceableCollectionType() {
        return new FuGECollectionReferenceableCollectionType();
    }

    /**
     * Create an instance of {@link FuGEBioMaterialGenericMaterialType.Components }
     * 
     */
    public FuGEBioMaterialGenericMaterialType.Components createFuGEBioMaterialGenericMaterialTypeComponents() {
        return new FuGEBioMaterialGenericMaterialType.Components();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolApplicationType.OutputMaterials }
     * 
     */
    public FuGECommonProtocolGenericProtocolApplicationType.OutputMaterials createFuGECommonProtocolGenericProtocolApplicationTypeOutputMaterials() {
        return new FuGECommonProtocolGenericProtocolApplicationType.OutputMaterials();
    }

    /**
     * Create an instance of {@link FuGECommonReferencesDatabaseType }
     * 
     */
    public FuGECommonReferencesDatabaseType createFuGECommonReferencesDatabaseType() {
        return new FuGECommonReferencesDatabaseType();
    }

    /**
     * Create an instance of {@link FuGEBioMaterialGenericMaterialType }
     * 
     */
    public FuGEBioMaterialGenericMaterialType createFuGEBioMaterialGenericMaterialType() {
        return new FuGEBioMaterialGenericMaterialType();
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementRangeType.UpperLimit }
     * 
     */
    public FuGECommonMeasurementRangeType.UpperLimit createFuGECommonMeasurementRangeTypeUpperLimit() {
        return new FuGECommonMeasurementRangeType.UpperLimit();
    }

    /**
     * Create an instance of {@link GELane }
     * 
     */
    public GELane createGELane() {
        return new GELane();
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementAtomicValueType }
     * 
     */
    public FuGECommonMeasurementAtomicValueType createFuGECommonMeasurementAtomicValueType() {
        return new FuGECommonMeasurementAtomicValueType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericParameterType }
     * 
     */
    public FuGECommonProtocolGenericParameterType createFuGECommonProtocolGenericParameterType() {
        return new FuGECommonProtocolGenericParameterType();
    }

    /**
     * Create an instance of {@link FuGECollectionAuditCollectionType }
     * 
     */
    public FuGECollectionAuditCollectionType createFuGECollectionAuditCollectionType() {
        return new FuGECollectionAuditCollectionType();
    }

    /**
     * Create an instance of {@link FuGECommonReferencesDatabaseReferenceType }
     * 
     */
    public FuGECommonReferencesDatabaseReferenceType createFuGECommonReferencesDatabaseReferenceType() {
        return new FuGECommonReferencesDatabaseReferenceType();
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementComplexValueType }
     * 
     */
    public FuGECommonMeasurementComplexValueType createFuGECommonMeasurementComplexValueType() {
        return new FuGECommonMeasurementComplexValueType();
    }

    /**
     * Create an instance of {@link FuGECollectionProviderType }
     * 
     */
    public FuGECollectionProviderType createFuGECollectionProviderType() {
        return new FuGECollectionProviderType();
    }

    /**
     * Create an instance of {@link FuGECommonAuditPersonType }
     * 
     */
    public FuGECommonAuditPersonType createFuGECommonAuditPersonType() {
        return new FuGECommonAuditPersonType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolSoftwareApplicationType }
     * 
     */
    public FuGECommonProtocolSoftwareApplicationType createFuGECommonProtocolSoftwareApplicationType() {
        return new FuGECommonProtocolSoftwareApplicationType();
    }

    /**
     * Create an instance of {@link FuGECommonAuditContactRoleType.Role }
     * 
     */
    public FuGECommonAuditContactRoleType.Role createFuGECommonAuditContactRoleTypeRole() {
        return new FuGECommonAuditContactRoleType.Role();
    }

    /**
     * Create an instance of {@link ParamListType }
     * 
     */
    public ParamListType createParamListType() {
        return new ParamListType();
    }

    /**
     * Create an instance of {@link GEGelMatrix }
     * 
     */
    public GEGelMatrix createGEGelMatrix() {
        return new GEGelMatrix();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolApplicationType.OutputData }
     * 
     */
    public FuGECommonProtocolGenericProtocolApplicationType.OutputData createFuGECommonProtocolGenericProtocolApplicationTypeOutputData() {
        return new FuGECommonProtocolGenericProtocolApplicationType.OutputData();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolEquipmentApplicationType }
     * 
     */
    public FuGECommonProtocolEquipmentApplicationType createFuGECommonProtocolEquipmentApplicationType() {
        return new FuGECommonProtocolEquipmentApplicationType();
    }

    /**
     * Create an instance of {@link MIAPEEquipmentType }
     * 
     */
    public MIAPEEquipmentType createMIAPEEquipmentType() {
        return new MIAPEEquipmentType();
    }

    /**
     * Create an instance of {@link GEImageAcquisitionEquipmentType }
     * 
     */
    public GEImageAcquisitionEquipmentType createGEImageAcquisitionEquipmentType() {
        return new GEImageAcquisitionEquipmentType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolType.Software }
     * 
     */
    public FuGECommonProtocolGenericProtocolType.Software createFuGECommonProtocolGenericProtocolTypeSoftware() {
        return new FuGECommonProtocolGenericProtocolType.Software();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericActionType.ActionTerm }
     * 
     */
    public FuGECommonProtocolGenericActionType.ActionTerm createFuGECommonProtocolGenericActionTypeActionTerm() {
        return new FuGECommonProtocolGenericActionType.ActionTerm();
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementRangeType.RangeDescriptors }
     * 
     */
    public FuGECommonMeasurementRangeType.RangeDescriptors createFuGECommonMeasurementRangeTypeRangeDescriptors() {
        return new FuGECommonMeasurementRangeType.RangeDescriptors();
    }

    /**
     * Create an instance of {@link GEElectrophoresisProtocol }
     * 
     */
    public GEElectrophoresisProtocol createGEElectrophoresisProtocol() {
        return new GEElectrophoresisProtocol();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolParameterPairType }
     * 
     */
    public FuGECommonProtocolParameterPairType createFuGECommonProtocolParameterPairType() {
        return new FuGECommonProtocolParameterPairType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolApplicationType.InputCompleteMaterials }
     * 
     */
    public FuGECommonProtocolGenericProtocolApplicationType.InputCompleteMaterials createFuGECommonProtocolGenericProtocolApplicationTypeInputCompleteMaterials() {
        return new FuGECommonProtocolGenericProtocolApplicationType.InputCompleteMaterials();
    }

    /**
     * Create an instance of {@link FuGECommonMeasurementRangeType.LowerLimit }
     * 
     */
    public FuGECommonMeasurementRangeType.LowerLimit createFuGECommonMeasurementRangeTypeLowerLimit() {
        return new FuGECommonMeasurementRangeType.LowerLimit();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolType }
     * 
     */
    public FuGECommonProtocolGenericProtocolType createFuGECommonProtocolGenericProtocolType() {
        return new FuGECommonProtocolGenericProtocolType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolParameterPairType.TargetParameter }
     * 
     */
    public FuGECommonProtocolParameterPairType.TargetParameter createFuGECommonProtocolParameterPairTypeTargetParameter() {
        return new FuGECommonProtocolParameterPairType.TargetParameter();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolParameterPairType.SourceParameter }
     * 
     */
    public FuGECommonProtocolParameterPairType.SourceParameter createFuGECommonProtocolParameterPairTypeSourceParameter() {
        return new FuGECommonProtocolParameterPairType.SourceParameter();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericEquipmentType.Software }
     * 
     */
    public FuGECommonProtocolGenericEquipmentType.Software createFuGECommonProtocolGenericEquipmentTypeSoftware() {
        return new FuGECommonProtocolGenericEquipmentType.Software();
    }

    /**
     * Create an instance of {@link FuGECommonReferencesBibliographicReferenceType }
     * 
     */
    public FuGECommonReferencesBibliographicReferenceType createFuGECommonReferencesBibliographicReferenceType() {
        return new FuGECommonReferencesBibliographicReferenceType();
    }

    /**
     * Create an instance of {@link MIAPESoftwareType }
     * 
     */
    public MIAPESoftwareType createMIAPESoftwareType() {
        return new MIAPESoftwareType();
    }

    /**
     * Create an instance of {@link FuGECommonOntologyUserParamType }
     * 
     */
    public FuGECommonOntologyUserParamType createFuGECommonOntologyUserParamType() {
        return new FuGECommonOntologyUserParamType();
    }

    /**
     * Create an instance of {@link FuGECommonOntologyCvParamType }
     * 
     */
    public FuGECommonOntologyCvParamType createFuGECommonOntologyCvParamType() {
        return new FuGECommonOntologyCvParamType();
    }

    /**
     * Create an instance of {@link GEMIAPEGE }
     * 
     */
    public GEMIAPEGE createGEMIAPEGE() {
        return new GEMIAPEGE();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericEquipmentType.EquipmentParts }
     * 
     */
    public FuGECommonProtocolGenericEquipmentType.EquipmentParts createFuGECommonProtocolGenericEquipmentTypeEquipmentParts() {
        return new FuGECommonProtocolGenericEquipmentType.EquipmentParts();
    }

    /**
     * Create an instance of {@link FuGEBioDataExternalDataType }
     * 
     */
    public FuGEBioDataExternalDataType createFuGEBioDataExternalDataType() {
        return new FuGEBioDataExternalDataType();
    }

    /**
     * Create an instance of {@link MIAPEContactType }
     * 
     */
    public MIAPEContactType createMIAPEContactType() {
        return new MIAPEContactType();
    }

    /**
     * Create an instance of {@link MIAPEParamUnitType }
     * 
     */
    public MIAPEParamUnitType createMIAPEParamUnitType() {
        return new MIAPEParamUnitType();
    }

    /**
     * Create an instance of {@link MIAPEProject }
     * 
     */
    public MIAPEProject createMIAPEProject() {
        return new MIAPEProject();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolActionApplicationType }
     * 
     */
    public FuGECommonProtocolActionApplicationType createFuGECommonProtocolActionApplicationType() {
        return new FuGECommonProtocolActionApplicationType();
    }

    /**
     * Create an instance of {@link GEProtocol }
     * 
     */
    public GEProtocol createGEProtocol() {
        return new GEProtocol();
    }

    /**
     * Create an instance of {@link FuGECommonAuditPersonType.Affiliations }
     * 
     */
    public FuGECommonAuditPersonType.Affiliations createFuGECommonAuditPersonTypeAffiliations() {
        return new FuGECommonAuditPersonType.Affiliations();
    }

    /**
     * Create an instance of {@link MIAPEBufferType }
     * 
     */
    public MIAPEBufferType createMIAPEBufferType() {
        return new MIAPEBufferType();
    }

    /**
     * Create an instance of {@link MIAPESubstanceType }
     * 
     */
    public MIAPESubstanceType createMIAPESubstanceType() {
        return new MIAPESubstanceType();
    }

    /**
     * Create an instance of {@link GESampleApplication }
     * 
     */
    public GESampleApplication createGESampleApplication() {
        return new GESampleApplication();
    }

    /**
     * Create an instance of {@link FuGECommonOntologyPropertyValue }
     * 
     */
    public FuGECommonOntologyPropertyValue createFuGECommonOntologyPropertyValue() {
        return new FuGECommonOntologyPropertyValue();
    }

    /**
     * Create an instance of {@link MIAPEGEEquipmentType }
     * 
     */
    public MIAPEGEEquipmentType createMIAPEGEEquipmentType() {
        return new MIAPEGEEquipmentType();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericProtocolApplicationType.InputData }
     * 
     */
    public FuGECommonProtocolGenericProtocolApplicationType.InputData createFuGECommonProtocolGenericProtocolApplicationTypeInputData() {
        return new FuGECommonProtocolGenericProtocolApplicationType.InputData();
    }

    /**
     * Create an instance of {@link FuGECommonProtocolGenericSoftwareType.Equipment }
     * 
     */
    public FuGECommonProtocolGenericSoftwareType.Equipment createFuGECommonProtocolGenericSoftwareTypeEquipment() {
        return new FuGECommonProtocolGenericSoftwareType.Equipment();
    }

    /**
     * Create an instance of {@link FuGECommonAuditOrganizationType.Parent }
     * 
     */
    public FuGECommonAuditOrganizationType.Parent createFuGECommonAuditOrganizationTypeParent() {
        return new FuGECommonAuditOrganizationType.Parent();
    }

    /**
     * Create an instance of {@link GEIndirectDetection }
     * 
     */
    public GEIndirectDetection createGEIndirectDetection() {
        return new GEIndirectDetection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolSoftwareApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SoftwareApplication")
    public JAXBElement<FuGECommonProtocolSoftwareApplicationType> createSoftwareApplication(FuGECommonProtocolSoftwareApplicationType value) {
        return new JAXBElement<FuGECommonProtocolSoftwareApplicationType>(_SoftwareApplication_QNAME, FuGECommonProtocolSoftwareApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonReferencesDatabaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Database")
    public JAXBElement<FuGECommonReferencesDatabaseType> createDatabase(FuGECommonReferencesDatabaseType value) {
        return new JAXBElement<FuGECommonReferencesDatabaseType>(_Database_QNAME, FuGECommonReferencesDatabaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonAuditOrganizationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Organization")
    public JAXBElement<FuGECommonAuditOrganizationType> createOrganization(FuGECommonAuditOrganizationType value) {
        return new JAXBElement<FuGECommonAuditOrganizationType>(_Organization_QNAME, FuGECommonAuditOrganizationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolActionApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ActionApplication")
    public JAXBElement<FuGECommonProtocolActionApplicationType> createActionApplication(FuGECommonProtocolActionApplicationType value) {
        return new JAXBElement<FuGECommonProtocolActionApplicationType>(_ActionApplication_QNAME, FuGECommonProtocolActionApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolParameterPairType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ParameterPair")
    public JAXBElement<FuGECommonProtocolParameterPairType> createParameterPair(FuGECommonProtocolParameterPairType value) {
        return new JAXBElement<FuGECommonProtocolParameterPairType>(_ParameterPair_QNAME, FuGECommonProtocolParameterPairType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolGenericSoftwareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericSoftware")
    public JAXBElement<FuGECommonProtocolGenericSoftwareType> createGenericSoftware(FuGECommonProtocolGenericSoftwareType value) {
        return new JAXBElement<FuGECommonProtocolGenericSoftwareType>(_GenericSoftware_QNAME, FuGECommonProtocolGenericSoftwareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGEBioMaterialGenericMaterialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericMaterial")
    public JAXBElement<FuGEBioMaterialGenericMaterialType> createGenericMaterial(FuGEBioMaterialGenericMaterialType value) {
        return new JAXBElement<FuGEBioMaterialGenericMaterialType>(_GenericMaterial_QNAME, FuGEBioMaterialGenericMaterialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonOntologyUserParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userParam")
    public JAXBElement<FuGECommonOntologyUserParamType> createUserParam(FuGECommonOntologyUserParamType value) {
        return new JAXBElement<FuGECommonOntologyUserParamType>(_UserParam_QNAME, FuGECommonOntologyUserParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonOntologyPropertyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PropertyValue")
    public JAXBElement<FuGECommonOntologyPropertyValue> createPropertyValue(FuGECommonOntologyPropertyValue value) {
        return new JAXBElement<FuGECommonOntologyPropertyValue>(_PropertyValue_QNAME, FuGECommonOntologyPropertyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonReferencesDatabaseReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DatabaseReference")
    public JAXBElement<FuGECommonReferencesDatabaseReferenceType> createDatabaseReference(FuGECommonReferencesDatabaseReferenceType value) {
        return new JAXBElement<FuGECommonReferencesDatabaseReferenceType>(_DatabaseReference_QNAME, FuGECommonReferencesDatabaseReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGEBioMaterialGenericMaterialMeasurementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericMaterialMeasurement")
    public JAXBElement<FuGEBioMaterialGenericMaterialMeasurementType> createGenericMaterialMeasurement(FuGEBioMaterialGenericMaterialMeasurementType value) {
        return new JAXBElement<FuGEBioMaterialGenericMaterialMeasurementType>(_GenericMaterialMeasurement_QNAME, FuGEBioMaterialGenericMaterialMeasurementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolGenericActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericAction")
    public JAXBElement<FuGECommonProtocolGenericActionType> createGenericAction(FuGECommonProtocolGenericActionType value) {
        return new JAXBElement<FuGECommonProtocolGenericActionType>(_GenericAction_QNAME, FuGECommonProtocolGenericActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolGenericParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericParameter")
    public JAXBElement<FuGECommonProtocolGenericParameterType> createGenericParameter(FuGECommonProtocolGenericParameterType value) {
        return new JAXBElement<FuGECommonProtocolGenericParameterType>(_GenericParameter_QNAME, FuGECommonProtocolGenericParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonDescriptionDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<FuGECommonDescriptionDescriptionType> createDescription(FuGECommonDescriptionDescriptionType value) {
        return new JAXBElement<FuGECommonDescriptionDescriptionType>(_Description_QNAME, FuGECommonDescriptionDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonAuditContactRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ContactRole")
    public JAXBElement<FuGECommonAuditContactRoleType> createContactRole(FuGECommonAuditContactRoleType value) {
        return new JAXBElement<FuGECommonAuditContactRoleType>(_ContactRole_QNAME, FuGECommonAuditContactRoleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolEquipmentApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EquipmentApplication")
    public JAXBElement<FuGECommonProtocolEquipmentApplicationType> createEquipmentApplication(FuGECommonProtocolEquipmentApplicationType value) {
        return new JAXBElement<FuGECommonProtocolEquipmentApplicationType>(_EquipmentApplication_QNAME, FuGECommonProtocolEquipmentApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolGenericProtocolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericProtocol")
    public JAXBElement<FuGECommonProtocolGenericProtocolType> createGenericProtocol(FuGECommonProtocolGenericProtocolType value) {
        return new JAXBElement<FuGECommonProtocolGenericProtocolType>(_GenericProtocol_QNAME, FuGECommonProtocolGenericProtocolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolGenericEquipmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericEquipment")
    public JAXBElement<FuGECommonProtocolGenericEquipmentType> createGenericEquipment(FuGECommonProtocolGenericEquipmentType value) {
        return new JAXBElement<FuGECommonProtocolGenericEquipmentType>(_GenericEquipment_QNAME, FuGECommonProtocolGenericEquipmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonOntologyCvType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cv")
    public JAXBElement<FuGECommonOntologyCvType> createCv(FuGECommonOntologyCvType value) {
        return new JAXBElement<FuGECommonOntologyCvType>(_Cv_QNAME, FuGECommonOntologyCvType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonOntologyCvParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cvParam")
    public JAXBElement<FuGECommonOntologyCvParamType> createCvParam(FuGECommonOntologyCvParamType value) {
        return new JAXBElement<FuGECommonOntologyCvParamType>(_CvParam_QNAME, FuGECommonOntologyCvParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECollectionReferenceableCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReferenceableCollection")
    public JAXBElement<FuGECollectionReferenceableCollectionType> createReferenceableCollection(FuGECollectionReferenceableCollectionType value) {
        return new JAXBElement<FuGECollectionReferenceableCollectionType>(_ReferenceableCollection_QNAME, FuGECollectionReferenceableCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolGenericProtocolApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericProtocolApplication")
    public JAXBElement<FuGECommonProtocolGenericProtocolApplicationType> createGenericProtocolApplication(FuGECommonProtocolGenericProtocolApplicationType value) {
        return new JAXBElement<FuGECommonProtocolGenericProtocolApplicationType>(_GenericProtocolApplication_QNAME, FuGECommonProtocolGenericProtocolApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonProtocolParameterValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ParameterValue")
    public JAXBElement<FuGECommonProtocolParameterValueType> createParameterValue(FuGECommonProtocolParameterValueType value) {
        return new JAXBElement<FuGECommonProtocolParameterValueType>(_ParameterValue_QNAME, FuGECommonProtocolParameterValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGEBioDataExternalDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExternalData")
    public JAXBElement<FuGEBioDataExternalDataType> createExternalData(FuGEBioDataExternalDataType value) {
        return new JAXBElement<FuGEBioDataExternalDataType>(_ExternalData_QNAME, FuGEBioDataExternalDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECollectionAuditCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuditCollection")
    public JAXBElement<FuGECollectionAuditCollectionType> createAuditCollection(FuGECollectionAuditCollectionType value) {
        return new JAXBElement<FuGECollectionAuditCollectionType>(_AuditCollection_QNAME, FuGECollectionAuditCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonReferencesBibliographicReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BibliographicReference")
    public JAXBElement<FuGECommonReferencesBibliographicReferenceType> createBibliographicReference(FuGECommonReferencesBibliographicReferenceType value) {
        return new JAXBElement<FuGECommonReferencesBibliographicReferenceType>(_BibliographicReference_QNAME, FuGECommonReferencesBibliographicReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECollectionProviderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Provider")
    public JAXBElement<FuGECollectionProviderType> createProvider(FuGECollectionProviderType value) {
        return new JAXBElement<FuGECollectionProviderType>(_Provider_QNAME, FuGECollectionProviderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuGECommonAuditPersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Person")
    public JAXBElement<FuGECommonAuditPersonType> createPerson(FuGECommonAuditPersonType value) {
        return new JAXBElement<FuGECommonAuditPersonType>(_Person_QNAME, FuGECommonAuditPersonType.class, null, value);
    }

}
