package org.proteored.miapeapi.xml.pride.ms;

import java.util.List;
import java.util.Set;

import org.proteored.miapeapi.cv.ControlVocabularyManager;
import org.proteored.miapeapi.cv.msi.DataTransformation;
import org.proteored.miapeapi.interfaces.ms.DataAnalysis;
import org.proteored.miapeapi.xml.pride.autogenerated.CvParamType;
import org.proteored.miapeapi.xml.pride.autogenerated.ParamType;
import org.proteored.miapeapi.xml.pride.util.PrideControlVocabularyXmlFactory;

import gnu.trove.set.hash.THashSet;

public class DataAnalysisManager {
	Set<DataAnalysis> ret = new THashSet<DataAnalysis>();

	public DataAnalysisManager(ParamType processingMethod, ControlVocabularyManager cvManager) {

		final List<CvParamType> cvParams = PrideControlVocabularyXmlFactory.getCvsFromParamType(processingMethod,
				DataTransformation.getInstance(cvManager));
		if (cvParams != null) {
			for (CvParamType cvParamType : cvParams) {
				ret.add(new DataAnalysisImpl(cvParamType));
			}

		}
	}

	public Set<DataAnalysis> getDataAnalysis() {
		if (!ret.isEmpty())
			return ret;
		return null;
	}

}
