package org.proteored.miapeapi.xml.ge;

import org.proteored.miapeapi.interfaces.ge.GEAdditionalInformation;
import org.proteored.miapeapi.xml.ge.autogenerated.ParamType;
import org.proteored.miapeapi.xml.ge.util.GEControlVocabularyXmlFactory;

public class AdditionalInformationImpl implements GEAdditionalInformation {
	private final ParamType additionalInformationXML;

	public AdditionalInformationImpl(
			ParamType geAdditionalInformation) {
		this.additionalInformationXML = geAdditionalInformation;
	}

	@Override
	public String getName() {
		return GEControlVocabularyXmlFactory.getName(this.additionalInformationXML);
	}

	@Override
	public String getValue() {
		return GEControlVocabularyXmlFactory.getValue(this.additionalInformationXML);
	}


}
