package org.proteored.miapeapi.xml.ge;

import org.proteored.miapeapi.interfaces.BufferComponent;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;
import org.proteored.miapeapi.xml.ge.util.GEControlVocabularyXmlFactory;

public class BufferComponentImpl extends SubstanceImpl implements BufferComponent {

	public BufferComponentImpl(MIAPESubstanceType substanceItem) {
		super(substanceItem);
	}

	@Override
	public String getName() {
		return GEControlVocabularyXmlFactory.getName(super.substanceXML.getName());
	}
}
