package org.proteored.miapeapi.xml.ge;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.proteored.miapeapi.interfaces.Buffer;
import org.proteored.miapeapi.interfaces.BufferComponent;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPEBufferType;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;
import org.proteored.miapeapi.xml.ge.util.GEControlVocabularyXmlFactory;
import org.proteored.miapeapi.xml.util.MiapeXmlUtil;

public class BufferImpl implements Buffer {
	private final MIAPEBufferType bufferXML;

	public BufferImpl(MIAPEBufferType bufferItem) {
		this.bufferXML = bufferItem;
	}

	@Override
	public Set<BufferComponent> getComponents() {
		Set<BufferComponent> setOfSubstance = new HashSet<BufferComponent>();
		List<MIAPESubstanceType> substanceList = bufferXML.getMIAPEBufferComponent();
		for (MIAPESubstanceType substanceItem : substanceList)
			setOfSubstance.add(new BufferComponentImpl(substanceItem));
		return setOfSubstance;
	}

	@Override
	public String getDescription() {
		return bufferXML.getDescription();
	}

	@Override
	public String getName() {
		return bufferXML.getName();
	}

	@Override
	public String getType() {
		return GEControlVocabularyXmlFactory.getName(bufferXML.getType());
	}

	@Override
	public int getId() {
		return MiapeXmlUtil.getIdFromXMLId(bufferXML.getId());
	}



}
