package org.proteored.miapeapi.xml.ge;

import org.proteored.miapeapi.interfaces.ge.DirectDetectionAgent;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;

public class DirectDetectionAgentImpl extends AgentImpl implements DirectDetectionAgent {

	public DirectDetectionAgentImpl(MIAPESubstanceType substanceItem) {
		super(substanceItem);

	}
}
