package org.proteored.miapeapi.xml.ge;

import org.proteored.miapeapi.interfaces.ge.IndirectDetectionAgent;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPESubstanceType;

public class IndirectDetectionAgentImpl extends AgentImpl implements IndirectDetectionAgent {

	public IndirectDetectionAgentImpl(MIAPESubstanceType substanceItem) {
		super(substanceItem);
	}

}
