package org.proteored.miapeapi.xml.ge;

import org.proteored.miapeapi.exceptions.MiapeDatabaseException;
import org.proteored.miapeapi.exceptions.MiapeSecurityException;
import org.proteored.miapeapi.interfaces.MiapeDate;
import org.proteored.miapeapi.interfaces.Project;
import org.proteored.miapeapi.interfaces.User;
import org.proteored.miapeapi.interfaces.persistence.PersistenceManager;
import org.proteored.miapeapi.xml.ge.autogenerated.MIAPEProject;

public class ProjectImpl implements Project {
	private final MIAPEProject projectXML;
	private final User owner;
	private final PersistenceManager dbManager;
	private int id = -1;

	public ProjectImpl(MIAPEProject project, User owner, PersistenceManager dbManager) {
		this.projectXML = project;
		this.owner = owner;
		this.dbManager = dbManager;

	}

	@Override
	public String getComments() {
		return projectXML.getComments();
	}

	@Override
	public MiapeDate getDate() {
		if (projectXML.getDate() != null) {

			return new MiapeDate(projectXML.getDate());
		}
		return null;
	}

	@Override
	public String getName() {
		return projectXML.getName();
	}

	@Override
	public User getOwner() {
		return owner;
	}

	@Override
	public int getId() {
		if (projectXML.getId() != null) {
			try {
				return Integer.valueOf(projectXML.getId());
			} catch (Exception e) {
				// do nothing
			}
		}
		return id;
	}

	@Override
	public int store() throws MiapeDatabaseException, MiapeSecurityException {
		if (this.dbManager != null) {
			id = dbManager.saveProject(this);
		}
		throw new MiapeDatabaseException("The persistance method is not defined.");
	}

	@Override
	public void delete(String userName, String password) throws MiapeDatabaseException, MiapeSecurityException {
		if (this.dbManager != null) {
			dbManager.deleteProjectById(this.getId(), userName, password);
		}
		throw new MiapeDatabaseException("The persistance method is not defined.");

	}

}
