package org.proteored.miapeapi.xml.util;

import java.util.List;

import org.proteored.miapeapi.xml.mzidentml.autogenerated.FuGECommonOntologyCvParamType;
import org.proteored.miapeapi.xml.pride.autogenerated.CvParamType;

import uk.ac.ebi.jmzidml.model.mzidml.CvParam;

public class CVUtils {

	/**
	 * Check if a param has a cvId equal than a given one
	 * 
	 * @param param
	 * @param cvId
	 * @return true if it is found or false if not
	 */
	public static boolean isThisCV(Object param, String cvId) {
		if (param == null)
			return false;
		if (cvId.equals(""))
			return false;

		// FuGECommonOntologyParamType from mzIdentML schema
		if (param instanceof FuGECommonOntologyCvParamType) {
			if (param != null && !cvId.equals("")) {
				FuGECommonOntologyCvParamType cvParam = (FuGECommonOntologyCvParamType) param;
				if (cvParam.getAccession().equals(cvId)) {
					return true;
				}
			}
		}

		// CvParamType from PRIDE schema
		if (param instanceof CvParamType) {
			if (param != null && !cvId.equals("")) {
				CvParamType cvParam = (CvParamType) param;
				if (cvParam.getAccession().equals(cvId)) {
					return true;
				}
			}
		}

		// CvParamType from mzIdentML_1_1 schema
		if (param instanceof CvParam) {
			if (param != null && !cvId.equals("")) {
				CvParam cvParam = (CvParam) param;
				if (cvParam.getAccession().equals(cvId)) {
					return true;
				}
			}
		}
		return false;
	}

	/**
	 * Iterate in the list to search for a param with a cvId
	 * 
	 * @param param
	 * @param cvId
	 * @return true if the cvId is found or false if not
	 */
	public static Object isThereThisCV(List<Object> param, String cvId) {
		if (param == null)
			return null;
		if (cvId.equals(""))
			return null;

		for (Object object : param) {
			boolean isThisCV = CVUtils.isThisCV(object, cvId);
			if (isThisCV)
				return object;
		}
		return null;
	}

}
