package org.proteored.miapeapi.xml.gi;

import org.proteored.miapeapi.interfaces.Algorithm;
import org.proteored.miapeapi.xml.gi.autogenerated.MIAPEAlgorithmType;
import org.proteored.miapeapi.xml.gi.util.Utils;

public class AlgorithmImpl implements Algorithm {
	private final MIAPEAlgorithmType xmlAlgorithm;
	public AlgorithmImpl(MIAPEAlgorithmType xmlAlgorithm) {
		this.xmlAlgorithm = xmlAlgorithm;
	}

	@Override
	public String getCatalogNumber() {
		return xmlAlgorithm.getCatalogNumber();
	}

	@Override
	public String getComments() {
		return xmlAlgorithm.getComments();
	}

	@Override
	public String getDescription() {
		return xmlAlgorithm.getDescription();
	}

	@Override
	public String getManufacturer() {
		return xmlAlgorithm.getManufacturer();
	}

	@Override
	public String getModel() {
		return xmlAlgorithm.getModel();
	}

	@Override
	public String getName() {
		return Utils.writeParam(xmlAlgorithm.getName());
	}

	@Override
	public String getParameters() {
		return xmlAlgorithm.getParameters();
	}

	@Override
	public String getURI() {
		return xmlAlgorithm.getURI();
	}

	@Override
	public String getVersion() {
		return xmlAlgorithm.getVersion();
	}

}
