package org.proteored.miapeapi.xml.gi;

import org.proteored.miapeapi.interfaces.gi.ImageProcessingStep;
import org.proteored.miapeapi.xml.gi.autogenerated.GIImageProcessingAlgorithmType;

public class ImageProcessingStepImpl extends AlgorithmImpl implements ImageProcessingStep {

	private final GIImageProcessingAlgorithmType imageProcessingAlgorithmXML;

	public ImageProcessingStepImpl(GIImageProcessingAlgorithmType imageProcessingStepXML) {
		super(imageProcessingStepXML);
		this.imageProcessingAlgorithmXML = imageProcessingStepXML;
	}

	@Override
	public String getStepOrder() {
		return imageProcessingAlgorithmXML.getStepOrder();
	}

}
