package org.proteored.miapeapi.xml.msi;

import org.proteored.miapeapi.interfaces.msi.AdditionalParameter;
import org.proteored.miapeapi.xml.msi.autogenerated.ParamType;
import org.proteored.miapeapi.xml.msi.util.MSIControlVocabularyXmlFactory;

public class AdditionalParameterImpl implements AdditionalParameter {
	private final ParamType xmlAdditionalParameter;



	public AdditionalParameterImpl(ParamType xmlAdditionalParameter2) {
		this.xmlAdditionalParameter = xmlAdditionalParameter2;
	}

	@Override
	public String getName() {
		return MSIControlVocabularyXmlFactory.getName(xmlAdditionalParameter);
	}

	@Override
	public String getValue() {
		return MSIControlVocabularyXmlFactory.getValue(xmlAdditionalParameter);
	}


}
