package org.proteored.miapeapi.xml.msi;

import org.proteored.miapeapi.interfaces.msi.Database;
import org.proteored.miapeapi.xml.msi.autogenerated.MSIDatabase;
import org.proteored.miapeapi.xml.msi.util.MSIControlVocabularyXmlFactory;

public class DatabaseImpl implements Database {
	private final MSIDatabase xmlDatabase;
	public DatabaseImpl(MSIDatabase xmlDatabase) {
		this.xmlDatabase = xmlDatabase;
	}

	@Override
	public String getDate() {
		return xmlDatabase.getDate();
	}

	@Override
	public String getDescription() {
		return xmlDatabase.getDescription();
	}

	@Override
	public String getName() {
		return MSIControlVocabularyXmlFactory.getName(xmlDatabase.getName());
	}

	@Override
	public String getNumVersion() {
		return xmlDatabase.getVersion();
	}

	@Override
	public String getSequenceNumber() {
		return xmlDatabase.getSequenceNumber();
	}

	@Override
	public String getUri() {
		return xmlDatabase.getURI();
	}

}
