package org.proteored.miapeapi.xml.pride;

import java.util.StringTokenizer;

import org.proteored.miapeapi.interfaces.User;
import org.proteored.miapeapi.interfaces.ms.MSContact;
import org.proteored.miapeapi.xml.pride.autogenerated.PersonType;

class ContactImpl implements MSContact {

	private final PersonType contact;
	private String lastName = "";
	private final User user;
	private String name = "";

	public ContactImpl(PersonType contact, User user) {
		this.contact = contact;
		this.user = user;
		if (contact.getName() != null) {
			StringTokenizer tokenizer = new StringTokenizer(contact.getName(), ",");
			// lastname, firstname
			if (tokenizer.countTokens() > 1) {
				lastName = tokenizer.nextToken();
			} else if (tokenizer.countTokens() == 1) {
				tokenizer = new StringTokenizer(contact.getName(), " ");
				if (tokenizer.countTokens() > 1) {
					// firstname lastname
					name = tokenizer.nextToken();
					lastName = tokenizer.nextToken();
				} else {
					// name??
					name = tokenizer.nextToken();
				}
			}
		}
	}

	@Override
	public String getAddress() {
		return null;
	}

	@Override
	public String getCP() {
		return null;
	}

	@Override
	public String getCountry() {
		return null;
	}

	@Override
	public String getDepartment() {
		return null;
	}

	@Override
	public String getEmail() {
		if (contact.getContactInfo() != null) {
			return contact.getContactInfo();
		}
		if (user != null && user.getEmail() != null) {
			return user.getEmail();
		}

		return "unknown@proteored.org";
	}

	@Override
	public String getFax() {
		return null;
	}

	@Override
	public String getInstitution() {
		return contact.getInstitution();
	}

	@Override
	public String getLastName() {
		return lastName;
	}

	@Override
	public String getLocality() {
		return null;
	}

	@Override
	public String getName() {
		if (contact.getName() != null) {
			return contact.getName();
		}
		if (user != null && user.getName() != null) {
			return user.getName();
		}
		return "Unknown";
	}

	@Override
	public String getTelephone() {
		return null;
	}

	@Override
	public String getPosition() {
		return null;
	}

}
