//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:51 PM CEST 
//


package org.proteored.miapeapi.xml.gelml.autogenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 *  Abstract superclass representing different methods of supplying a value or measurement. 
 * 
 * <p>Java class for FuGE.Common.Measurement.MeasurementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FuGE.Common.Measurement.MeasurementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataType" type="{http://www.psidev.info/gelml/1_1candidate}FuGE.Common.Ontology.cvParamType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FuGE.Common.Measurement.MeasurementType", propOrder = {
    "dataType"
})
@XmlSeeAlso({
    FuGECommonMeasurementBooleanValueType.class,
    FuGECommonMeasurementRangeType.class,
    FuGECommonMeasurementAtomicValueType.class,
    FuGECommonMeasurementComplexValueType.class
})
public abstract class FuGECommonMeasurementMeasurementType {

    protected FuGECommonOntologyCvParamType dataType;

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link FuGECommonOntologyCvParamType }
     *     
     */
    public FuGECommonOntologyCvParamType getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuGECommonOntologyCvParamType }
     *     
     */
    public void setDataType(FuGECommonOntologyCvParamType value) {
        this.dataType = value;
    }

}
