//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:51 PM CEST 
//


package org.proteored.miapeapi.xml.gelml.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  A Protocol defining how samples are loaded onto a Gel or GelLanes.
 *    
 * 
 * <p>Java class for GelML.SampleLoading.SampleLoadingProtocolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GelML.SampleLoading.SampleLoadingProtocolType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psidev.info/gelml/1_1candidate}FuGE.Common.Protocol.ProtocolType">
 *       &lt;sequence>
 *         &lt;element name="protocolText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loadingBuffer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}AddBufferAction"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}GenericParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sampleLoadingEquipment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="GenericEquipment_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GelML.SampleLoading.SampleLoadingProtocolType", propOrder = {
    "protocolText",
    "loadingBuffer",
    "genericParameter",
    "sampleLoadingEquipment"
})
public class GelMLSampleLoadingSampleLoadingProtocolType
    extends FuGECommonProtocolProtocolType
{

    @XmlElement(required = true)
    protected String protocolText;
    protected GelMLSampleLoadingSampleLoadingProtocolType.LoadingBuffer loadingBuffer;
    @XmlElement(name = "GenericParameter")
    protected List<FuGECommonProtocolGenericParameterType> genericParameter;
    protected List<GelMLSampleLoadingSampleLoadingProtocolType.SampleLoadingEquipment> sampleLoadingEquipment;

    /**
     * Gets the value of the protocolText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolText() {
        return protocolText;
    }

    /**
     * Sets the value of the protocolText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolText(String value) {
        this.protocolText = value;
    }

    /**
     * Gets the value of the loadingBuffer property.
     * 
     * @return
     *     possible object is
     *     {@link GelMLSampleLoadingSampleLoadingProtocolType.LoadingBuffer }
     *     
     */
    public GelMLSampleLoadingSampleLoadingProtocolType.LoadingBuffer getLoadingBuffer() {
        return loadingBuffer;
    }

    /**
     * Sets the value of the loadingBuffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GelMLSampleLoadingSampleLoadingProtocolType.LoadingBuffer }
     *     
     */
    public void setLoadingBuffer(GelMLSampleLoadingSampleLoadingProtocolType.LoadingBuffer value) {
        this.loadingBuffer = value;
    }

    /**
     * Gets the value of the genericParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FuGECommonProtocolGenericParameterType }
     * 
     * 
     */
    public List<FuGECommonProtocolGenericParameterType> getGenericParameter() {
        if (genericParameter == null) {
            genericParameter = new ArrayList<FuGECommonProtocolGenericParameterType>();
        }
        return this.genericParameter;
    }

    /**
     * Gets the value of the sampleLoadingEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sampleLoadingEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSampleLoadingEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GelMLSampleLoadingSampleLoadingProtocolType.SampleLoadingEquipment }
     * 
     * 
     */
    public List<GelMLSampleLoadingSampleLoadingProtocolType.SampleLoadingEquipment> getSampleLoadingEquipment() {
        if (sampleLoadingEquipment == null) {
            sampleLoadingEquipment = new ArrayList<GelMLSampleLoadingSampleLoadingProtocolType.SampleLoadingEquipment>();
        }
        return this.sampleLoadingEquipment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}AddBufferAction"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addBufferAction"
    })
    public static class LoadingBuffer {

        @XmlElement(name = "AddBufferAction", required = true)
        protected GelMLElectrophoresisAddBufferActionType addBufferAction;

        /**
         * Gets the value of the addBufferAction property.
         * 
         * @return
         *     possible object is
         *     {@link GelMLElectrophoresisAddBufferActionType }
         *     
         */
        public GelMLElectrophoresisAddBufferActionType getAddBufferAction() {
            return addBufferAction;
        }

        /**
         * Sets the value of the addBufferAction property.
         * 
         * @param value
         *     allowed object is
         *     {@link GelMLElectrophoresisAddBufferActionType }
         *     
         */
        public void setAddBufferAction(GelMLElectrophoresisAddBufferActionType value) {
            this.addBufferAction = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="GenericEquipment_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SampleLoadingEquipment {

        @XmlAttribute(name = "GenericEquipment_ref", required = true)
        protected String genericEquipmentRef;

        /**
         * Gets the value of the genericEquipmentRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGenericEquipmentRef() {
            return genericEquipmentRef;
        }

        /**
         * Sets the value of the genericEquipmentRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGenericEquipmentRef(String value) {
            this.genericEquipmentRef = value;
        }

    }

}
