//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:51 PM CEST 
//


package org.proteored.miapeapi.xml.gelml.autogenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *  Abstract superclass representing the groups of ProtocolApplications that
 *     should be represented in a valid GelML document. 
 * 
 * <p>Java class for GelML.GelMLRoot.GelExperimentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GelML.GelMLRoot.GelExperimentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psidev.info/gelml/1_1candidate}FuGE.Common.IdentifiableType">
 *       &lt;sequence>
 *         &lt;element name="electrophoresisType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}cvParam"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}ContactRole" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GelML.GelMLRoot.GelExperimentType", propOrder = {
    "electrophoresisType",
    "contactRole"
})
@XmlSeeAlso({
    GelMLGelMLRootGel2DExperimentType.class,
    GelMLGelMLRootGel1DExperimentType.class,
    GelMLGelMLRootOtherGelExperimentType.class
})
public abstract class GelMLGelMLRootGelExperimentType
    extends FuGECommonIdentifiableType
{

    protected GelMLGelMLRootGelExperimentType.ElectrophoresisType electrophoresisType;
    @XmlElement(name = "ContactRole")
    protected FuGECommonAuditContactRoleType contactRole;
    @XmlAttribute
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the electrophoresisType property.
     * 
     * @return
     *     possible object is
     *     {@link GelMLGelMLRootGelExperimentType.ElectrophoresisType }
     *     
     */
    public GelMLGelMLRootGelExperimentType.ElectrophoresisType getElectrophoresisType() {
        return electrophoresisType;
    }

    /**
     * Sets the value of the electrophoresisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GelMLGelMLRootGelExperimentType.ElectrophoresisType }
     *     
     */
    public void setElectrophoresisType(GelMLGelMLRootGelExperimentType.ElectrophoresisType value) {
        this.electrophoresisType = value;
    }

    /**
     * The primary contact for this GelExperiment
     * 
     * @return
     *     possible object is
     *     {@link FuGECommonAuditContactRoleType }
     *     
     */
    public FuGECommonAuditContactRoleType getContactRole() {
        return contactRole;
    }

    /**
     * The primary contact for this GelExperiment
     * 
     * @param value
     *     allowed object is
     *     {@link FuGECommonAuditContactRoleType }
     *     
     */
    public void setContactRole(FuGECommonAuditContactRoleType value) {
        this.contactRole = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}cvParam"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cvParam"
    })
    public static class ElectrophoresisType {

        @XmlElement(required = true)
        protected FuGECommonOntologyCvParamType cvParam;

        /**
         * Gets the value of the cvParam property.
         * 
         * @return
         *     possible object is
         *     {@link FuGECommonOntologyCvParamType }
         *     
         */
        public FuGECommonOntologyCvParamType getCvParam() {
            return cvParam;
        }

        /**
         * Sets the value of the cvParam property.
         * 
         * @param value
         *     allowed object is
         *     {@link FuGECommonOntologyCvParamType }
         *     
         */
        public void setCvParam(FuGECommonOntologyCvParamType value) {
            this.cvParam = value;
        }

    }

}
