//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:51 PM CEST 
//


package org.proteored.miapeapi.xml.gelml.autogenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 *  A sample excised from a gel. These materials can be referenced by formats
 *     modelling other techniques, such as mass spectrometry. 
 * 
 * <p>Java class for GelML.Excision.ExcisedSampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GelML.Excision.ExcisedSampleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psidev.info/gelml/1_1candidate}FuGE.Bio.Material.MaterialType">
 *       &lt;attribute name="GelLocation_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GelML.Excision.ExcisedSampleType")
public class GelMLExcisionExcisedSampleType
    extends FuGEBioMaterialMaterialType
{

    @XmlAttribute(name = "GelLocation_ref", required = true)
    protected String gelLocationRef;

    /**
     * Gets the value of the gelLocationRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGelLocationRef() {
        return gelLocationRef;
    }

    /**
     * Sets the value of the gelLocationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGelLocationRef(String value) {
        this.gelLocationRef = value;
    }

}
