//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:51 PM CEST 
//


package org.proteored.miapeapi.xml.gelml.autogenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 *  Circle is for defining a circular location on an image. 
 * 
 * <p>Java class for GelML.Excision.CircleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GelML.Excision.CircleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psidev.info/gelml/1_1candidate}GelML.Excision.FeatureLocationType">
 *       &lt;attribute name="pixelRadius" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GelML.Excision.CircleType")
public class GelMLExcisionCircleType
    extends GelMLExcisionFeatureLocationType
{

    @XmlAttribute(required = true)
    protected int pixelRadius;

    /**
     * Gets the value of the pixelRadius property.
     * 
     */
    public int getPixelRadius() {
        return pixelRadius;
    }

    /**
     * Sets the value of the pixelRadius property.
     * 
     */
    public void setPixelRadius(int value) {
        this.pixelRadius = value;
    }

}
