//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 07:25:51 PM CEST 
//


package org.proteored.miapeapi.xml.gelml.autogenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  The gel matrix used in any dimension of an electrophoresis assay.
 *    
 * 
 * <p>Java class for GelML.Gel.GelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GelML.Gel.GelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.psidev.info/gelml/1_1candidate}FuGE.Bio.Material.MaterialType">
 *       &lt;sequence>
 *         &lt;element name="gelType" type="{http://www.psidev.info/gelml/1_1candidate}ParamType" minOccurs="0"/>
 *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}GelLane" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="componentGels" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}Gel" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="percentAcrylamide" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{http://www.psidev.info/gelml/1_1candidate}MeasurementGroup"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}AcrylamideToCrossLinker" minOccurs="0"/>
 *         &lt;element name="otherGelConstituents" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="GenericMaterial_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="model" type="{http://www.psidev.info/gelml/1_1candidate}ParamType" minOccurs="0"/>
 *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}Dimensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="separationDimension" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="batchNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GelML.Gel.GelType", propOrder = {
    "gelType",
    "gelLane",
    "componentGels",
    "percentAcrylamide",
    "acrylamideToCrossLinker",
    "otherGelConstituents",
    "model",
    "dimensions"
})
public class GelMLGelGelType
    extends FuGEBioMaterialMaterialType
{

    protected ParamType gelType;
    @XmlElement(name = "GelLane")
    protected List<GelMLGelGelLaneType> gelLane;
    protected GelMLGelGelType.ComponentGels componentGels;
    protected GelMLGelGelType.PercentAcrylamide percentAcrylamide;
    @XmlElement(name = "AcrylamideToCrossLinker")
    protected GelMLGelAcrylamideToCrossLinkerType acrylamideToCrossLinker;
    protected List<GelMLGelGelType.OtherGelConstituents> otherGelConstituents;
    protected ParamType model;
    @XmlElement(name = "Dimensions")
    protected GelMLGelDimensionsType dimensions;
    @XmlAttribute
    protected Integer separationDimension;
    @XmlAttribute
    protected String batchNumber;

    /**
     * Gets the value of the gelType property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getGelType() {
        return gelType;
    }

    /**
     * Sets the value of the gelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setGelType(ParamType value) {
        this.gelType = value;
    }

    /**
     * Gets the value of the gelLane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gelLane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGelLane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GelMLGelGelLaneType }
     * 
     * 
     */
    public List<GelMLGelGelLaneType> getGelLane() {
        if (gelLane == null) {
            gelLane = new ArrayList<GelMLGelGelLaneType>();
        }
        return this.gelLane;
    }

    /**
     * Gets the value of the componentGels property.
     * 
     * @return
     *     possible object is
     *     {@link GelMLGelGelType.ComponentGels }
     *     
     */
    public GelMLGelGelType.ComponentGels getComponentGels() {
        return componentGels;
    }

    /**
     * Sets the value of the componentGels property.
     * 
     * @param value
     *     allowed object is
     *     {@link GelMLGelGelType.ComponentGels }
     *     
     */
    public void setComponentGels(GelMLGelGelType.ComponentGels value) {
        this.componentGels = value;
    }

    /**
     * Gets the value of the percentAcrylamide property.
     * 
     * @return
     *     possible object is
     *     {@link GelMLGelGelType.PercentAcrylamide }
     *     
     */
    public GelMLGelGelType.PercentAcrylamide getPercentAcrylamide() {
        return percentAcrylamide;
    }

    /**
     * Sets the value of the percentAcrylamide property.
     * 
     * @param value
     *     allowed object is
     *     {@link GelMLGelGelType.PercentAcrylamide }
     *     
     */
    public void setPercentAcrylamide(GelMLGelGelType.PercentAcrylamide value) {
        this.percentAcrylamide = value;
    }

    /**
     * Gets the value of the acrylamideToCrossLinker property.
     * 
     * @return
     *     possible object is
     *     {@link GelMLGelAcrylamideToCrossLinkerType }
     *     
     */
    public GelMLGelAcrylamideToCrossLinkerType getAcrylamideToCrossLinker() {
        return acrylamideToCrossLinker;
    }

    /**
     * Sets the value of the acrylamideToCrossLinker property.
     * 
     * @param value
     *     allowed object is
     *     {@link GelMLGelAcrylamideToCrossLinkerType }
     *     
     */
    public void setAcrylamideToCrossLinker(GelMLGelAcrylamideToCrossLinkerType value) {
        this.acrylamideToCrossLinker = value;
    }

    /**
     * Gets the value of the otherGelConstituents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherGelConstituents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherGelConstituents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GelMLGelGelType.OtherGelConstituents }
     * 
     * 
     */
    public List<GelMLGelGelType.OtherGelConstituents> getOtherGelConstituents() {
        if (otherGelConstituents == null) {
            otherGelConstituents = new ArrayList<GelMLGelGelType.OtherGelConstituents>();
        }
        return this.otherGelConstituents;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setModel(ParamType value) {
        this.model = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link GelMLGelDimensionsType }
     *     
     */
    public GelMLGelDimensionsType getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link GelMLGelDimensionsType }
     *     
     */
    public void setDimensions(GelMLGelDimensionsType value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the separationDimension property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeparationDimension() {
        return separationDimension;
    }

    /**
     * Sets the value of the separationDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeparationDimension(Integer value) {
        this.separationDimension = value;
    }

    /**
     * Gets the value of the batchNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * Sets the value of the batchNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchNumber(String value) {
        this.batchNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.psidev.info/gelml/1_1candidate}Gel" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gel"
    })
    public static class ComponentGels {

        @XmlElement(name = "Gel", required = true)
        protected List<GelMLGelGelType> gel;

        /**
         * Gets the value of the gel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GelMLGelGelType }
         * 
         * 
         */
        public List<GelMLGelGelType> getGel() {
            if (gel == null) {
                gel = new ArrayList<GelMLGelGelType>();
            }
            return this.gel;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="GenericMaterial_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OtherGelConstituents {

        @XmlAttribute(name = "GenericMaterial_ref", required = true)
        protected String genericMaterialRef;

        /**
         * Gets the value of the genericMaterialRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGenericMaterialRef() {
            return genericMaterialRef;
        }

        /**
         * Sets the value of the genericMaterialRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGenericMaterialRef(String value) {
            this.genericMaterialRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://www.psidev.info/gelml/1_1candidate}MeasurementGroup"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "atomicValue",
        "booleanValue",
        "complexValue",
        "range"
    })
    public static class PercentAcrylamide {

        @XmlElement(name = "AtomicValue")
        protected FuGECommonMeasurementAtomicValueType atomicValue;
        @XmlElement(name = "BooleanValue")
        protected FuGECommonMeasurementBooleanValueType booleanValue;
        @XmlElement(name = "ComplexValue")
        protected FuGECommonMeasurementComplexValueType complexValue;
        @XmlElement(name = "Range")
        protected FuGECommonMeasurementRangeType range;

        /**
         * Gets the value of the atomicValue property.
         * 
         * @return
         *     possible object is
         *     {@link FuGECommonMeasurementAtomicValueType }
         *     
         */
        public FuGECommonMeasurementAtomicValueType getAtomicValue() {
            return atomicValue;
        }

        /**
         * Sets the value of the atomicValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link FuGECommonMeasurementAtomicValueType }
         *     
         */
        public void setAtomicValue(FuGECommonMeasurementAtomicValueType value) {
            this.atomicValue = value;
        }

        /**
         * Gets the value of the booleanValue property.
         * 
         * @return
         *     possible object is
         *     {@link FuGECommonMeasurementBooleanValueType }
         *     
         */
        public FuGECommonMeasurementBooleanValueType getBooleanValue() {
            return booleanValue;
        }

        /**
         * Sets the value of the booleanValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link FuGECommonMeasurementBooleanValueType }
         *     
         */
        public void setBooleanValue(FuGECommonMeasurementBooleanValueType value) {
            this.booleanValue = value;
        }

        /**
         * Gets the value of the complexValue property.
         * 
         * @return
         *     possible object is
         *     {@link FuGECommonMeasurementComplexValueType }
         *     
         */
        public FuGECommonMeasurementComplexValueType getComplexValue() {
            return complexValue;
        }

        /**
         * Sets the value of the complexValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link FuGECommonMeasurementComplexValueType }
         *     
         */
        public void setComplexValue(FuGECommonMeasurementComplexValueType value) {
            this.complexValue = value;
        }

        /**
         * Gets the value of the range property.
         * 
         * @return
         *     possible object is
         *     {@link FuGECommonMeasurementRangeType }
         *     
         */
        public FuGECommonMeasurementRangeType getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link FuGECommonMeasurementRangeType }
         *     
         */
        public void setRange(FuGECommonMeasurementRangeType value) {
            this.range = value;
        }

    }

}
