package org.proteored.miapeapi.xml.msi.adapter;

import org.proteored.miapeapi.cv.msi.DatabaseName;
import org.proteored.miapeapi.interfaces.Adapter;
import org.proteored.miapeapi.interfaces.msi.Database;
import org.proteored.miapeapi.xml.msi.autogenerated.MSIDatabase;
import org.proteored.miapeapi.xml.msi.autogenerated.ObjectFactory;
import org.proteored.miapeapi.xml.msi.util.MSIControlVocabularyXmlFactory;

public class DatabaseAdapter implements Adapter<MSIDatabase> {
	private final Database database;
	private final ObjectFactory factory;
	private final MSIControlVocabularyXmlFactory cvFactory;

	public DatabaseAdapter(Database database, ObjectFactory factory,
			MSIControlVocabularyXmlFactory cvFactory) {
		this.database = database;
		this.factory = factory;
		this.cvFactory = cvFactory;
	}

	@Override
	public MSIDatabase adapt() {
		MSIDatabase xmlDatabase = factory.createMSIDatabase();
		xmlDatabase.setDate(database.getDate());
		xmlDatabase.setDescription(database.getDescription());
		xmlDatabase.setName(cvFactory.createCV(database.getName(), null,
				DatabaseName.getInstance(cvFactory.getCvManager())));
		xmlDatabase.setSequenceNumber(database.getSequenceNumber());
		xmlDatabase.setURI(database.getUri());
		xmlDatabase.setVersion(database.getNumVersion());
		return xmlDatabase;
	}

}
